### ISSUE TITLE
Create issue & pull request templates

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#10]
- [ ]  when I create an issue there is a choice of template
- [ ] when I create a pull request there is a template

**Comment by katjam** [comment]
Verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/b306c097-5a25-439e-b301-26ba4f9341a8)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/b8957c8a-6c2a-4ab8-a45d-7b97337186ad)
