### ISSUE TITLE
Add a How to use this website page and link from footer

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#104]
## Acceptance Criteria

- [ ] There is a link in the footer to a "How to use this website" page
- [ ] There helpful copy on the "How to use this website" page
- [ ] I can edit the how to page in the cms

**Comment by katjam** [comment]
Question is around what the content of this page should be.

**Comment by undividual** [comment]
Note: Autumn is going to work on content for this shortly!

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/9d59e8b1-bea7-4e55-8cec-e63f4c2ef0dc)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/8d620687-fe18-4280-8b41-047b4df2e41d)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/c93272a0-e292-4d84-9db3-e5c48a2ba1be)
