### ISSUE TITLE
Use NextDoorNature, not TeamWilder

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#107]
## Description
Change references of TeamWilder to NextDoorNature

TeamWilder is not a campaign. It is a way of thinking. Not to be used as a brand/in this way.
We need to get ‘NextDoorNature’ into the copy more. 

## Acceptance Criteria

- [ ] `find src/ -type f | xargs grep -i --color "team\\s*wilder"` should return nothing
- [ ] The correct wording for this is "Nextdoor Nature"
- [ ] @ivan-kocienski-gfsc draft and get @undividual to confirm

## Plan

- [ ] Scan for "team" in codebase
- [ ] Remove/change name
- [ ] rename local directory
- [ ] rename repo on GH (?)

**Comment by ivan-kocienski-gfsc** [comment]
Is there specific capitalisation on this? 

"Nextdoor Nature"

"NextDoor Nature"

"Next Door Nature"
