### ISSUE TITLE
Sweep for [cCc]

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#109]
## Acceptance Criteria

- [ ] Copy does not contain any [cCc] flags
- [x] #257 
- [ ] The approved copy is added to the master copy doc by The Wildlife trust: https://docs.google.com/spreadsheets/d/1pkcokDOMpE8GIasIzsbs97xB0ZCnAi1VaQOiTC-vQ-U/edit?usp=sharing
- [ ] The copy in the app as as per the approved en and approved cy columns and marked in green
- [ ] The temporary copy column is empty

## Plan

- [x] Add the approved copy and mark green.
- [x] This will be iterative & have a few PRs against it.

## Outstanding from 20th June

- [ ] [cCc] content in the welsh versions of how to use this site and share your survey (both markdown docs)
- [ ] [cCc] content for two keys: SearchMetaDescription and IndexMetaDescription

**Comment by katjam** [comment]
ee because need to source the copy or get approved.

**Comment by ivan-kocienski-gfsc** [comment]
Here is the key/text table from the code.



copy key | [cCc] Guides | intent of copy | approved en copy | approved cy copy
-- | -- | -- | -- | --
SiteTitle | The Nextdoor Nature Library |   |   |  
ChangeLanguage | [cCc] Switch to Welsh |   |   |  
Story404Title | [cCc] Sorry, we can't find that story |   |   |  
Story404Body | [cCc] Try searching again [home](\"\\\") |   |   |  
Guide404Title | [cCc] Sorry, we can't find that guide |   |   |  
Guide404Slug | guide-not-found |   |   |  
Guide404Body | [cCc] Try searching again [home](\"\\\" |   |   |  
AncillaryPage404Slug | page-not-found |   |   |  
AncillaryPage404Title | [cCc] Sorry, we can't find that page |   |   |  
AncillaryPage404Body | [cCc] Try searching again [home](\"\\\" |   |   |  
FooterTitleColumnA | [cCc] Find out more |   |   |  
FooterTitleColumnB | [cCc] Explore the library |   |   |  
FooterTitleColumnC | [cCc] Get involved |   |   |  
FooterVisitWebsiteText | [cCc] Visit the Wildlife Trusts' main website |   |   |  
FooterVisitWebsiteLink | https://www.wildlifetrusts.org/ |   |   |  
FooterAboutText | Find out more about this project |   |   |  
FooterAboutLink | /about |   |   |  
FooterGuidesLinkText | [cCc] Browse our guides |   |   |  
FooterGuidesLink | /guides |   |   |  
FooterFindYourLocalTrustText | [cCc] Find your local trust |   |   |  
FooterFindYourLocalTrustLink | https://www.wildlifetrusts.org/wildlife-trusts |   |   |  
FooterPrivacyPolicyText | Privacy Policy |   |   |  
FooterPrivacyPolicyLink | /privacy-policy |   |   |  
FooterSiteLogo | Nextdoor Nature |   |   |  
FooterCharityInfo | [cCc] The Nextdoor Nature online library is a project by the Wildlife Trusts: Protecting Wildlife for the Future |   |   |  
RegisteredCharityNumber | Registered charity number 20723 |   |   |  
CookieBannerH2 | Are you ok to proceed with all cookies and data? |   |   |  
CookieBannerP | [cCc] Our website uses cookies and data to make sure you have the best experience and to help us fundraise efficiently to save wildlife. Some cookies are essential to make our website work. |   |   |  
CookieAcceptButtonText | Okay, got it |   |   |  
CookieDeclineButtonText | No thanks |   |   |  
CookieSettingsButtonText | Cookie settings |   |   |  
IndexExploreGuidesByThemeTitle | [cCc] Explore Guides by Theme |   |   |  
WelcomeP1 | [cCc] Nextdoor Nature is an initiative launched by the Wilidlife Trusts in 2022. (Read more here) The aim of Nextdoor Nature is to equip everyone with the skills and knowledge they need to make a positive difference for nature - in their own area, and beyond. |   |   |  
WelcomeP2 | [cCc] With the climate and environmental crisis ever worsining, it's important to recognise that there are actions all of us can take that can meaniningfully make a difference. It's easy to feel powerless, but in fact, together we are powerful! |   |   |  
WelcomeP3 | [cCc] The goal of Nextdoor Nature is to get at least 1 in 4 people across the UK taking Action for Nature. This online library aims to support anyone who is interested in finding out what they can do, and how they can get other people involved. |   |   |  
RelatedGuidesHeading | Related Guides |   |   |  
RelatedStoriesHeading | Real Stories |   |   |  
GuidesTitle | [cCc] Guides |   |   |  
SearchPlaceholder | Search the library |   |   |  
ExploreGuidesListPlaceholder | [cCc] Explore guides by theme |   |   |  


There is also some text in `index.html` for the `<title>`

**Comment by katjam** [comment]
Question: Get approved copy from @AutumnBarlow

**Comment by ivan-kocienski-gfsc** [comment]
So this is the complete table with all the keys present (for reference)

copy key | [cCc] Guides | intent of copy | approved en copy | approved cy copy
-- | -- | -- | -- | --
SiteTitle | The Nextdoor Nature Hub | Main site title | The Nextdoor Nature Hub | Hwb Natur Drws-nesaf
ChangeLanguage | [cCc] Switch to Welsh | Switch language link in header |   |  
Story404Title | [cCc] Sorry, we can't find that story | appears on 404 page |   |  
Story404Body | [cCc] Try searching again [home](\"\\\") |   |   |  
Guide404Title | [cCc] Sorry, we can't find that guide |   |   |  
Guide404Slug | guide-not-found | n/a |   |  
Guide404Body | [cCc] Try searching again [home](\"\\\" |   |   |  
AncillaryPage404Slug | page-not-found | n/a |   |  
AncillaryPage404Title | [cCc] Sorry, we can't find that page |   |   |  
AncillaryPage404Body | [cCc] Try searching again [home](\"\\\" |   |   |  
FooterTitleColumnA | [cCc] Find out more | Appears in footer on every page |   |  
FooterTitleColumnB | [cCc] Explore the library | Appears in footer on every page |   |  
FooterTitleColumnC | [cCc] Get involved | Appears in footer on every page |   |  
FooterVisitWebsiteText | [cCc] Visit the Wildlife Trusts' main website |   |   |  
FooterVisitWebsiteLink | https://www.wildlifetrusts.org/ | n/a |   |  
FooterAboutText | Find out more about this project |   | Find out more about this project |  
FooterAboutLink | /about | n/a |   |  
FooterGuidesLinkText | [cCc] Browse our guides |   |   |  
FooterGuidesLink | /guides | n/a |   |  
FooterFindYourLocalTrustText | [cCc] Find your local trust |   |   |  
FooterFindYourLocalTrustLink | https://www.wildlifetrusts.org/wildlife-trusts | n/a |   |  
FooterPrivacyPolicyText | Privacy Policy |   | Privacy Policy |  
FooterPrivacyPolicyLink | /privacy-policy | n/a |   |  
FooterSiteLogo | Nextdoor Nature | text that makes up logo in footer | Nextdoor Nature | Natur Drws-nesaf
FooterCharityInfo | [cCc] The Nextdoor Nature online library is a project by the Wildlife Trusts: Protecting Wildlife for the Future |   |   |  
RegisteredCharityNumber | Registered charity number 20723 |   | Registered charity number 20723 |  
CookieBannerH2 | Are you ok to proceed with all cookies and data? | cookie banner | Are you ok to proceed with all cookies and data? |  
CookieBannerP | [cCc] Our website uses cookies and data to make sure you have the best experience and to help us fundraise efficiently to save wildlife. Some cookies are essential to make our website work. | cookie banner |   |  
CookieAcceptButtonText | Okay, got it |   | Okay, got it |  
CookieDeclineButtonText | No thanks |   | No thanks |  
CookieSettingsButtonText | Cookie settings |   | Cookie settings |  
IndexExploreGuidesByThemeTitle | [cCc] Explore Guides by Theme | not used |   |  
WelcomeP1 | [cCc] Nextdoor Nature is an initiative launched by the Wilidlife Trusts in 2022. (Read more here) The aim of Nextdoor Nature is to equip everyone with the skills and knowledge they need to make a positive difference for nature - in their own area, and beyond. | is on front page index |   |  
WelcomeP2 | [cCc] With the climate and environmental crisis ever worsining, it's important to recognise that there are actions all of us can take that can meaniningfully make a difference. It's easy to feel powerless, but in fact, together we are powerful! | is on front page index |   |  
WelcomeP3 | [cCc] The goal of Nextdoor Nature is to get at least 1 in 4 people across the UK taking Action for Nature. This online library aims to support anyone who is interested in finding out what they can do, and how they can get other people involved. | is on front page index |   |  
RelatedGuidesHeading | Related Guides | on show guide page | Related Guides |  
RelatedStoriesHeading | Real Stories | on show guide page | Real Stories |  
GuidesTitle | [cCc] Guides | on guides list page |   |  
SearchPlaceholder | Search the library | search box placeholder text | Search the library |  
ExploreGuidesListPlaceholder | [cCc] Explore guides by theme | n/a (dev placeholder text that will be removed by launch) |   |

**Comment by undividual** [comment]
Autumn is going to look at getting all of this approved.

Question for you (dev team) — is this a comprehensive list of all copy on the site that will need translating into Welsh, as per #257? If not, can we get this to Autumn?

**Comment by r-ferrier** [comment]
@undividual it's a list of everything on the site that we have added, but not the content that Autumn has added - anything that has come in via the CMS is not included in this. The best place to get that list from is probably the CMS itself, Autumn has access to everything there.

**Comment by undividual** [comment]
Okay great, so in that case @AutumnBarlow my understanding is that the above list IS the comprehensive list of all you need for Welsh translation (i.e. any other content that needs translating is accessible to you via the CMS)

**Comment by katjam** [comment]
FYI, I deleted the out of date copy tables from this ticket.
