### ISSUE TITLE
Use NextDoorNature colours

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#110]
## Acceptance Criteria

- [ ] The tinted background uses purple and teal NextDoorNature colours 

## Specifications

Teal hex code is #058295, and I have used it at 10% tint in the background (#e7f2f4).
Purple hex code is #54257F

## Plan

- [ ] define global colors in common theme module
- [ ] apply to relevant parts
  - [ ] background of all pages should be light teal
  - [ ] background of header should be teal
  - [ ] background of footer should be purple
  - [ ] headers and anchors should be purple

**Comment by undividual** [comment]
The below design screenshot shows this implemented. 
Teal hex code is #058295, and I have used it at 10% tint in the background.
Purple hex code is #54257F

![MVPWireframes_1Homepage](https://user-images.githubusercontent.com/90701712/232233559-d2ca688d-dee4-4380-90c3-8b18c1668484.jpg)
