### ISSUE TITLE
Darken top header bar

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#111]
## Acceptance Criteria

- [ ] make the top bar darker or otherwise weightier to make it clear it’s the top of the website (TBC on colour with Emma)

## Plan

- [ ] Step one to achieve this

**Comment by undividual** [comment]
The below design shows this implemented. 
Teal hex code is #058295
Purple hex code is #54257F

![MVPWireframes_1Homepage](https://user-images.githubusercontent.com/90701712/232233700-3ec2f7b1-03f7-4f80-b388-3ae7f183d452.jpg)

**Comment by aaaaargZombies** [comment]
depends on #140

**Comment by ivan-kocienski-gfsc** [comment]
I think this will be resolved when #138 was merged
