### ISSUE TITLE
Define responsive layout container

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#113]
## Questions

- How wide is widest with 3 columns? do we space between or outsides.
- What is the min & max on columns?
- TBC - dev to discuss with Emma
- This may differ on home & other pages (i.e. there may be 3 or more layouts)

## Plan

- [x] #134
- [x] Decide on some sensible breakpoints
- [x] Decide on some sensible margin sizes & padding
- [x] Create some generic css utility classes for things like padding (a clearfix-type block)
- [x] Create the required layout classes for use in default pages
- [ ] #143
- [ ] #144
- [ ] #145

## Linked task

- [ ] Update notion to add in some CSS snippets for useful utility vars

**Comment by katjam** [comment]
This was blocked by this meeting https://www.notion.so/gfsc/CSS-studio-conventions-5164e6bb94ec4cf3b790a5e837d5a172?pvs=4. Now is OK to work on.

**Comment by r-ferrier** [comment]
Layouts here: https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/Team-wilder-layouts
