### ISSUE TITLE
Use the right fonts

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#115]
## Acceptance criteria

- [ ] The fonts used for the body are correct (Rubik)
- [ ] The fonts used for headers are correct (Adelle)
- [ ] The fonts used for other headers are correct (Ludicrous)

## Implementation notes & questions

@undividual what are the fonts that we should be using?

**Comment by undividual** [comment]
The typefaces are:
Adelle (The serif one)
Rubik (The sans serif one)

And we have had sign off from the WTs about these being their correct brand typefaces.

**Comment by katjam** [comment]
@undividual Do you have the font files downloaded from them? I think WOFF / WOFF2 are all we need but we might want EOT & TTF also legacy fallbacks. 

It's better to bundle them in than to rely on linking out to them - but we should probably ask the IT team how they prefer us to include as it'll be their adobe account. (maybe a dev can take a sneak peak how they are included in the other sites).

**Comment by undividual** [comment]
I have the additional typeface (nextdoornature brand) 'ludicrous' (here https://www.dropbox.com/sh/e2jo5g631kw2fjd/AABjX0XZZw9JFw4p-nGXcyUDa?dl=0)

However Adelle and Rubik are both Adobe fonts, so I cannot access the font files. (That old chestnut, but — these are their brand fonts, so we have to use them. Likely they are loading them in direct from adobe on their main website too, might be worth asking them how they implement them though)

**Comment by undividual** [comment]
I don't have enough technical knowledge to know if this is a good idea or not — I don't THINK we wanna use this for headings anywhere else but it would be nice to keep our options open. Does the typeface not work?
