### ISSUE TITLE
An ancillary page has an English and a Welsh version

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#120]
## Issue

Ancillary pages (about, privacy policy etc) also need to be available in welsh.

This may be duplicated by #117 

How do we handle this? Do we have language folders (cy, eng) & separate markdown files, or do we have single markdown files with (cy, eng) language fields?

Blocked by #7

**Comment by r-ferrier** [comment]
This is blocked by #62 - it can follow the same pattern as this once it's merged

**Comment by ivan-kocienski-gfsc** [comment]
The files do exist (so no missing content) but they are not translated (?)
