### ISSUE TITLE
[Bug]: Routing doesn't work on netlify

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#131]
## Description

Netlify will correctly route you to a page if you click a link to get there but not if you enter it as a url or refresh. This is only a relevant bug if we decide to use netlify hosting for production.

## Steps to reproduce

1. Visit the homepage in the netlify hosted version of the site & click on a link to a guide
2. Refresh the page

OR

1. Edit the url for a guide into the address bar

**Comment by katjam** [comment]
fixed
