### ISSUE TITLE
list of cookies in privacy policy matches cookies used in site

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#132]
## Issue

The cookies we use need to match those listed in the privacy policy

## Acceptance criteria

- [ ] Specific cookies listed in the privacy policy for hotjar, google, and the wildlife trust are the same as the specific cookies we use

**Comment by ivan-kocienski-gfsc** [comment]
I would think FormStack would use cookies as well. Should we add this in now or make an issue specifically for when that PR is merged?

**Comment by ivan-kocienski-gfsc** [comment]
I just checked on localhost and the cookies I have found are:

```
Google
  _ga
  _ga

Hotjar
  _hjSessionUser_3123140





Unknown:
  hubspotutk
  amp_cebfd0
  ajs_user_id
  ajs_anonymous_id
  __ssid
  __hstc
  BetterErrors-has-used-console

  Google?
    _ga_X2FMMZSSS9
    _ga_D3VTD4SBDZ
    ga-cookie-consent
```

**Comment by ivan-kocienski-gfsc** [comment]
Questions

* Is there a way we can word this so as to not need to keep doing this? 
* Is there a reason we need to keep record of the specific keys?
* Is this something the WT does and if so how do they keep on top of their cookies? (can this be automated?) or is their stuff also out of date?
* Also I find the wording of the cookie banner to be disingenuous - we are asking the user if they want cookies but if they click "no" then (we only try to turn off the google tracking system) we keep all the cookies around anyway (we don't delete any of them that have been set, which sort of nullifies the whole "i don't consent" wording)

**Comment by katjam** [comment]
This ticket is to make sure the privacy policy text matches what we do with cookies.

The cookies we use are set in session which means they expire when the session is closed. Google and Hotjar take care of their own cookies & expiries.

We should not be setting our (functional cookie) unless they opt in. If google or hotjar are laying down cookies before they opt in, we should fix that.

**Comment by katjam** [comment]
Verified & is editable in CMS:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/e3114f56-5462-426e-a665-32690a85cf41)
