### ISSUE TITLE
someone from team wilder has approved privacy policy copy

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#133]
## Issue

Our privacy policy needs to be signed off by someone from team wilder. At the moment it is an exact copy of their english policy, with a couple of changes made to cookies

## Acceptance criteria
- [ ] English policy has been written & approved
- [ ] Welsh policy has been written & approved

**Comment by undividual** [comment]
FYI — Autumn following up on this now.

**Comment by ivan-kocienski-gfsc** [comment]
Hi @AutumnBarlow (or @undividual) did we get the privacy-policy copy signed off yet?

**Comment by AutumnBarlow** [comment]
Sorry - no, it needs to be the updated version June 2023, I don't know what the changes are so was just going to copy/paste the latest version onto the page in the CMS. Will do now.

**Comment by aaaaargZombies** [comment]
Just a note that I've updated cookies in this PR #444

**Comment by aaaaargZombies** [comment]
I'm closing this as Autumn has confirmed it's up to date except for technical details we are providing

**Comment by katjam** [comment]
Is editable in CMS:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/191a35ad-6708-4e4d-816e-f8406e51b290)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/31758dd7-1915-47f6-aab1-950beb41fc2f)
