### ISSUE TITLE
[Bug]: external actions should be pulled from live API

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/teamwilder#135]
## Description

I was unable to load action data from the wildlife trusts API as I was not making a request from an approved domain

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

repsonse header to my request

```
HTTP/2 200 OK
cache-control: max-age=3600, public
content-language: en
content-type: application/vnd.api+json
etag: "1681896063"
expires: Sun, 19 Nov 1978 05:00:00 GMT
last-modified: Wed, 19 Apr 2023 09:21:03 GMT
permissions-policy: interest-cohort=()
server: nginx
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-drupal-cache: MISS
x-drupal-dynamic-cache: MISS
x-frame-options: SAMEORIGIN
x-generator: Drupal 9 (https://www.drupal.org)
x-pantheon-styx-hostname: styx-fe3-a-6484fbc486-h6vc7
x-styx-req-id: 81623893-de93-11ed-a928-760e3b1d6b4b
x-ua-compatible: IE=edge
date: Wed, 19 Apr 2023 09:36:37 GMT
x-served-by: cache-chi-kigq8000090-CHI, cache-lon4280-LON
x-cache: MISS, HIT
x-cache-hits: 0, 1
x-timer: S1681896997.101998,VS0,VE1
vary: Cookie
age: 930
accept-ranges: bytes
via: 1.1 varnish, 1.1 varnish
content-length: 280537
X-Firefox-Spdy: h2
```

## Steps to reproduce

replace the url in this function with the API end point 

https://github.com/geeksforsocialchange/teamwilder/blob/31-remote-actions/src/Main.elm#L83
https://www.wildlifetrusts.org/jsonapi/node/action

## Dev notes

As far as I can see this URL is accessible by `curl`. So it should be a case of putting together a script to ingest the JSON and produce some kind of output payload that can be deployed like a static file. Then we need to rebuild/deploy the site periodically

**Comment by aaaaargZombies** [comment]
If we are asking TWT to update the API it would be really nice if they were willing to add the following to the attributes to the action nodes.

- thumbnail image url
- full text so we can search it

**Comment by ivan-kocienski-gfsc** [comment]
Weird seems to work when I curl it from the command line. May want to put together some kind of script that can embed some payload on deploy and rebuild it on the hour (or whenever).

**Comment by ivan-kocienski-gfsc** [comment]
@aaaaargZombies and @katjam is there a specific design for this?

It feels like this is a feature but it lacks any specific requirements or specifications about how it manifests on the front-end or how it should look.

**Comment by katjam** [comment]
@ivan-kocienski-gfsc The bug is this CORS issue "I was unable to load action data from the wildlife trusts API as I was not making a request from an approved domain"

Our initial intent was to pull the actions data in on request so it was always fresh. I think this issue is conflated with deciding whether to cache the info in a recurring build - especially since it looks like we'd have to do a lot of requests to get all the images.

We should probably split it out. Good call.

**Comment by r-ferrier** [comment]
closing as it has been revealed we no longer want this! Hoorah! #307

**Comment by katjam** [comment]
We do still want these - but I'll leave closed for now.
