### ISSUE TITLE
Set up Copy / Translation system for UI text

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#14]
## Acceptance criteria
- [ ] I can toggle between "placeholder Welsh" and English

**Comment by katjam** [comment]
@ivan-kocienski-gfsc Here are some relevant files to model on. Obviously this is only part of the picture, so let me know if you have trouble fitting together.
[TranslationExample.zip](https://github.com/geeksforsocialchange/teamwilder/files/10908656/TranslationExample.zip)

**Comment by r-ferrier** [comment]
verified:

Works for whole markdown pages

![Screenshot 2023-05-29 at 14 41 17](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/1f5f33fc-6078-4110-9b25-cec8e13dfdfc)
![Screenshot 2023-05-29 at 14 41 12](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/0bf01c1d-40b3-4829-ac0f-3a7d9a11f9d6)

Works for keys

![Screenshot 2023-05-29 at 14 30 16](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/8ac89369-2d40-4f7b-9772-b21a137efb25)
![Screenshot 2023-05-29 at 14 41 24](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/c68c3186-e354-436e-a616-99f802884e5f)
