### ISSUE TITLE
[Bug]: Missing header regression

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/teamwilder#140]
## Description

We introduced a regression here

https://github.com/geeksforsocialchange/teamwilder/pull/124/files#diff-0438047f0b53c3a6beb5820cedf6921bf3df851c765fade650d5f62de7379659R24

when sorting out the multiple h1 titles issue.

I gave this EE because although it will be easy to just pop back in we need to make sure we don't reintroduce #99 

## Acceptance Criteria

- [ ] Header is visible on all pages
- [ ] Header has correct color
- [ ] NDN Logo in correct font (not as an `<h1>`)

## Platform (if relevant)

What device and browser were you using?

**Comment by r-ferrier** [comment]
verified - header is on every page and is h1 on homepage
