### ISSUE TITLE
Create layout & style classes for header

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#143]
## Issue

Create layout classes for header & add (placeholder?) content as per image.

## Acceptance Criteria

https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/Team-wilder-layouts

![Screenshot 2023-04-21 at 14 01 20](https://user-images.githubusercontent.com/46496391/233642696-ef37c571-3dd3-4074-a2a6-99cf1b5a9702.png)

**Comment by r-ferrier** [comment]
blocked by #113

**Comment by katjam** [comment]
Should the translate toggle also be in this header?

**Comment by r-ferrier** [comment]
verified:

<img width="1474" alt="Screenshot 2023-05-30 at 09 41 31" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/95a58a18-6fa0-4403-a609-85a757456bf9">

<img width="480" alt="Screenshot 2023-05-30 at 09 56 51" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/e39963d2-96b6-40b0-9e25-a3de0613ae08">
