### ISSUE TITLE
Make guide teasers display at the same size and with consistent margins

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#145]
## Issue

Create layout classes for teasers

## Acceptance Criteria

https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/Team-wilder-layouts

![Screenshot 2023-04-21 at 14 01 50](https://user-images.githubusercontent.com/46496391/233642912-0d98c9bd-6214-4efa-8cb3-7e9e91226071.png)

**Comment by r-ferrier** [comment]
blocked by #113

**Comment by r-ferrier** [comment]
These are looking a little squiffy when the text is different lengths or when they are distributed unevenly - we could do more here to stop images from resizing differently

<img width="392" alt="Screenshot 2023-05-30 at 10 11 41" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/1449867f-e522-47fd-a2dd-4383dd6321a1">
<img width="298" alt="Screenshot 2023-05-30 at 10 10 46" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/e6515797-e305-494a-8768-4852fd8b1677">
<img width="287" alt="Screenshot 2023-05-30 at 10 12 47" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/9a2f18c0-bde7-4e2b-97c4-85342c6e3dcb">

**Comment by r-ferrier** [comment]
linked in #219

**Comment by aaaaargZombies** [comment]
## Verified


https://github.com/geeksforsocialchange/teamwilder/assets/6824891/00a97a22-3e62-48d3-a7dc-96cfa4ac9f85
