### ISSUE TITLE
Welsh language footer logos

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/teamwilder#146]
## User story

As a Welsh speaker I'd like to see the footer logos switch language along with the rest of the site.

## Missing images

- [ ] Welsh language image for The Lottery Heritage Foundation
- [ ]  Welsh image for the Queens Platinum Jubilee
- [ ]  Welsh image for the Wildlife Trusts wales 

## Implementation notes & questions

Replace logos in `public/images/*-cy.svg` with correct language versions

**Comment by r-ferrier** [comment]
@undividual These are the missing logos

**Comment by r-ferrier** [comment]
I did find this one but it's an EPS and would need converting to SVG or similar. The queens platinum trust ones are broken links now and the wildlife trusts wales only have a very low res version of their logo on their website with a white background.   

[Welsh_Made_possible_logo_Colour_EPS.eps.zip](https://github.com/geeksforsocialchange/teamwilder/files/11320296/Welsh_Made_possible_logo_Colour_EPS.eps.zip)

**Comment by undividual** [comment]
You'll see I've emailed them — I thought I'd be able to make these but when I cracked open the illustrator files I now see all the links are missing so I can't access the original versions! Sorry if I was misunderstanding and that's what you were saying all along :) Anyway I've cc'd you so hopefully you'll get them directly.

**Comment by katjam** [comment]
Closing as won't fix unless they supply logos
