### ISSUE TITLE
[Bug]: Make cookie banner sticky

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#150]
## Description
The cookie banner or cookie settings toggle button should always be visible at the bottom of the page

## Steps to reproduce

1. What you did first
1. What you did next

## Platform (if relevant)

What device and browser were you using?

**Comment by r-ferrier** [comment]
verified:

<img width="384" alt="Screenshot 2023-05-30 at 10 06 37" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/56c05203-796d-4661-aed2-c6c32ca3c2a7">
<img width="1264" alt="Screenshot 2023-05-30 at 10 06 45" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/d6024b91-2dd8-46ae-8797-6108c1cbe31a">
