### ISSUE TITLE
[Bug]: Some form of Scroll to top needs implementing

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#162]
## Description

When navigating the site internally scroll position is remembered. We need to implement some sort of scroll to top function on page load.

## Steps to reproduce

1. Visit the site, and scroll down the page
2. Click on an internal link

## Platform (if relevant)

Chrome, on a mac

**Comment by aaaaargZombies** [comment]
https://github.com/geeksforsocialchange/teamwilder/assets/6824891/db0c3e9a-c0c6-4195-9dbb-6aebe3137aa8

**Comment by katjam** [comment]
There is a standard implementation. Ask @katjam for the code.

**Comment by katjam** [comment]
### To implement the scroll
```
resetViewportTop : Cmd Msg
resetViewportTop =
    Task.perform (\_ -> NoOp) (Browser.Dom.setViewport 0 0)
```

### For accessibility to change focus to the correct element
```
resetFocusTop : Cmd Msg
resetFocusTop =
    Task.attempt (\_ -> NoOp) (Browser.Dom.focus "focus-target")
```

Add to the h1 attribute on all pages:
`h1 [ id "focus-target", tabindex -1 ][ text "My page heading" ]`

In the `UrlChanged` update function:
add `Cmd.batch [ resetFocusTop, resetViewportTop ]`

**Comment by r-ferrier** [comment]
I *think* It should be on the h1 because then this is what the page focuses on for screenreaders etc and is the first thing you want to hit, and also there is only ever one of these per page unless you are doing bad design. Which we are not 😅

**Comment by ivan-kocienski-gfsc** [comment]
Also I have this mostly implemented but now when you scroll to a link (on page A) and click to go to page B (with the window scrolled to the top) when you click back page A has scrolled to the top again, which is annoying.

Is there a way to get it to not scroll to top when navigating back?

**Comment by ivan-kocienski-gfsc** [comment]
> I _think_ It should be on the h1 because then this is what the page focuses on for screenreaders etc and is the first thing you want to hit, and also there is only ever one of these per page unless you are doing bad design. Which we are not sweat_smile

I only ask because we do only have the one `h1` per page but in the code `h1` is defined multiple places which may open us up to bugs if we don't make them all align.

```
ivan@localhost ~/work/teamwilder $ ack h1 src/
src/css/reset.css
11:h1,

src/Theme/Markdown.elm
41:                    Html.h1 [ css [ headerStyle ] ] children

src/Theme/Global.elm
118:        , typeSelector "h1"

src/Page/Index.elm
3:import Html.Styled exposing (Html, div, h1, p, text)
22:        [ h1 []

src/Page/Guide/View.elm
4:import Html.Styled exposing (Html, a, div, h1, h2, img, li, text, ul)
23:        [ h1 [ css [ guideTitleStyle ] ] [ text guide.title ]

src/Page/Story/View.elm
4:import Html.Styled exposing (Html, div, h1, img, p, text)
16:        [ h1 [] [ text story.title ]

src/Page/View.elm
3:import Html.Styled exposing (Html, div, h1, text)
14:        [ h1 [] [ text page.title ]

src/Page/Guides/View.elm
3:import Html.Styled exposing (Html, a, div, h1, img, li, p, text, ul)
42:        [ h1 []


```

**Comment by r-ferrier** [comment]
This works on every page except guides. I think @katjam mentioned disabling this on guides due to how searching works on the page, but if you've accessed guides by clicking on the link from the footer this doesn't make sense currently - maybe we need to refocus on clicking that link too
