### ISSUE TITLE
Search bar matches the wireframe

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#165]
## Acceptance criteria

- [x] search bar has a border radius
- [ ] ~search bar placeholder text is purple & bold~
- [x] search bar has an arrow icon
- [x] search bar has a purple border
- [ ] #308
- [ ] Placeholder text is "Find a guide"
- [x] "Find a guide" label exists but is hidden

<img width="424" alt="Screenshot 2023-04-25 at 09 28 51" src="https://user-images.githubusercontent.com/46496391/234223085-9bd4a624-1843-4add-82c0-3141590527f6.png">

**Comment by katjam** [comment]
Also not sure if the placeholder text is bold and maybe the lightened colour differs on platforms.

**Comment by katjam** [comment]
Reopening - we need to change.

**Comment by katjam** [comment]
Also been thinking, is it a terrible idea to have the search bos on the home page and have it be a button that looks like a search box - or have the functionality that it automatically navigates to search page when user searches.

Given that our usability testing showed people were very keen to see a search box up front, I think we may be letting people down.

**Comment by katjam** [comment]
Research - make sure the design we settle on can be / is accessible. 

Question - Talk to @undividual about expectations in terms of visibility on homepage & design.

**Comment by undividual** [comment]
Please let me know if you have any other direct questions around design for accessibility — I agree that 'search the library' might need to move outside the search box to the left, and also now we're not calling it a library, I think we can safely shorten it to just 'search:'

**Comment by r-ferrier** [comment]
@undividual we're worried that if we just have "search" then it will look like you can search the entire website, which is not possible - all you can do is find a guide. I'd like to suggest we:

- make the copy "find a guide"
- The copy should sit inside the box as placeholder text (this is supported everywhere now and is standard practice, we will add a hidden label for screenreaders)
- Make the search bar visible on every page

What do you think?

**Comment by undividual** [comment]
Ahh I see what you mean. I like 'find a guide', and I think we're pretty much agreed that's what we're calling these, right? (I assume the search ALSO searches case studies, but like, I don't think that detail matters and the search can still refer to 'guides'). 
I agree with all your suggestions above.

**Comment by r-ferrier** [comment]
@undividual I actually don't think it does search case studies - only guides - but we don't have any case studies yet in any case! Is that something that it needs to be able to do? We may want to add a ticket for that to the backlog if so, so let me know.

**Comment by r-ferrier** [comment]
Have updated the AC

**Comment by undividual** [comment]
Hmmm, I do really think it should — will that be very difficult/a lot of extra work? If it WILL be, we should speak to Autumn about how essential this is.

**Comment by r-ferrier** [comment]
Ok will put the question label back on this and maybe we can discuss on Monday because I'm not sure!

**Comment by undividual** [comment]
Yes — makes sense, and thanks for the explainer! Let's just mention this to Autumn then but say we won't prioritise it until later (if there is a later)

**Comment by AutumnBarlow** [comment]
I have begun adding a few stories and aim to have many more to upload this week. However, they are not intrinsic to any guide in particular - the stories are a huge draw to the site as we are emphasising how this is a community thing, that people can upload their own stories and discover those of others in similar situations to themselves. It may be of more use to tag and categorise the stories so that they are easy to browse.

**Comment by katjam** [comment]
Closing as covered elsewhere.

**Comment by aaaaargZombies** [comment]
## Verified

updated copy

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/a4836cb5-3d2f-4c75-a3e3-36e8218c8e80)

![2023-06-21-12:08:53-screenshot](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/aec5a03a-62ad-4f83-9647-296707d193b6)
