### ISSUE TITLE
Font Sizes sensible at desktop & mobile

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#166]
## Acceptance criteria

- [ ] Heading tags are used hierarchically
- [ ] Headings are bold
- [ ] Headings are smaller at mobile when required (may not be an issue for some of the smaller headings)
- [ ] At mobile tie logo font size to VW instead of rem so that it stretches to fit width of screen? (just a thought!)

![Screenshot 2023-04-25 at 09 45 14](https://user-images.githubusercontent.com/46496391/234224799-b37296a5-66e7-4c77-ac20-b7de75ac5049.png)
![Screenshot 2023-04-25 at 09 47 50](https://user-images.githubusercontent.com/46496391/234224787-90800f12-a5b4-4527-81fd-ae3c0dd8327a.png)
![Screenshot 2023-04-25 at 09 47 42](https://user-images.githubusercontent.com/46496391/234224789-8eee1975-2198-4e11-ae78-2ef4cdcebb76.png)
![Screenshot 2023-04-25 at 09 47 33](https://user-images.githubusercontent.com/46496391/234224792-f70d9f89-d934-4702-9e0a-6339137641db.png)
![Screenshot 2023-04-25 at 09 45 27](https://user-images.githubusercontent.com/46496391/234224797-6585ab09-c7fe-4ac2-99fc-b80e0e284c42.png)

**Comment by katjam** [comment]
Desktop (ignore the sticky cookie - it's the screenchot software)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/cd4e7522-820d-4f30-bf82-53cd3e5aa389)

Tablet:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/3e0f779d-3bc6-4377-8ca4-d346f8341dd1)


Mobile:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/bf659282-4ae3-4068-a738-f41710623f7d)

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/2f46b03d-2947-4e14-81ef-be0605453de4)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/ab30e73f-a68e-4ced-89a7-7e5d6f36c5b2)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/7441d397-e692-4163-bd30-08e445038e7c)

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/b58babcd-16c3-4b8e-bcbe-bd2f3edb0be7)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/71faaad4-d9d9-4e1d-b238-462bf4981cf0)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/33f62906-885f-49aa-b71b-51d202379792)
