### ISSUE TITLE
Image dimensions pinned to 1:1 aspect ratio for highlights

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#167]
## Acceptance criteria

- [x] Thumbnail images are clipped to be square

<img width="254" alt="Screenshot 2023-04-25 at 09 27 41" src="https://user-images.githubusercontent.com/46496391/234225155-f8d723f1-58b9-4d07-b442-19ffba27e51a.png">

**Comment by katjam** [comment]
Verified:

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/77f5e25e-13ec-4424-a900-5a8c6e60ca35)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/68ba1886-fb63-44f1-bf0f-b8be64a141e4)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/be49440c-ae2b-44bf-9a3d-d679524a453f)
