### ISSUE TITLE
List styling matches wireframe

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#169]
## Acceptance criteria

List style A (Home page list of guides to explore)
- [ ] Title for each item is bold & purple
- [ ] Summary restricted to two lines
- [ ] Purple arrow at end
- [ ] Entire entry clickable

List style B (footer, related guides)
- [ ] Each item is just a title, not bold
- [ ] Purple arrow at end

![Screenshot 2023-04-25 at 09 53 06](https://user-images.githubusercontent.com/46496391/234226633-b0298584-48d9-4ea9-a0e9-567c8d165cf2.png)
![Screenshot 2023-04-25 at 09 52 59](https://user-images.githubusercontent.com/46496391/234226636-9d5a754c-96a2-48f6-a33b-d02f5555bca2.png)

**Comment by ivan-kocienski-gfsc** [comment]
i think "summary restricted to two lines" might be a bit tricky (unless there's some CSS fu that can be employed).

we don't have any firm control over how large text is rendered on page (from code) so the best we can do is either pull the text out of the database and tell the content writers to keep it short or forcibly cut strings off at a certain point that will approximate the correct dimensions when rendered.

**Comment by ivan-kocienski-gfsc** [comment]
The section "Explore Guides by Theme" appears to need coding in the `Index.elm` template as well as styling (unless i am missing something)

**Comment by ivan-kocienski-gfsc** [comment]
Is there even a data source for these links in the model?

**Comment by katjam** [comment]
Part of other styling sweep
