### ISSUE TITLE
Colour usage matches wireframe

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#170]
## Acceptance criteria

- [ ] Borders around each section are correct colour (Does the border frame the content on wider screens, or go to the edge of the screen? May need to experiment to see which looks best)
- [ ] Text is the correct colour
- [ ] Backgrounds are the correct colour

https://miro.com/app/board/uXjVPyf-Msw=/

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/18cb6c3a-271a-457e-a09e-0a13fb9906be)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/4ea4f29d-ad26-419c-8a22-d36c6e6edbea)

@undividual there is a question here about the intention of the border. It's not really noticeable if we have it pegged to the edges of the sreen. Do you want us to add some padding outside of it?

**Comment by undividual** [comment]
It's meant to be subtle, so I think stick with it as it is? I just visited the test site and it looks exactly as I intended.
