### ISSUE TITLE
[Bug]: Header looks different on different pages

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#175]
## Description

The logo in the top left hand corner looks bolder on the home page than on the other pages

## Steps to reproduce

1. Visit the guides page
2. Click the logo to return to the home page
3. FLUMP!

**Comment by katjam** [comment]
@r-ferrier @ivan-kocienski-gfsc It doesn't look different as suggested by the AC by it is a link on pages that are not the home page and it is an h1 only on the homepage. I am assuming that is sufficient, but running it past you just in case.

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/a59e3603-ce3b-4580-81a4-32a9b314cc26)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/533afc70-357b-4139-9878-79ec9e0b2fcc)
