### ISSUE TITLE
Make explore guides by theme list

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/teamwilder#178]
## User story

As a person visiting the site I would like to see a list of themes that the guides cover so I can find guides related to a given subject I am interested in.

## Acceptance criteria

- [ ] list of guides by theme (using categories) is present on the index landing page
- [ ] all existing guides have categories (if in doubt ask Autumn which one)

## Implementation plan

- data is hard coded for now
- put in a route (or a search arg) that can show guides by theme
- guide tagging?

**Comment by katjam** [comment]
Related to #193 - revisit after that

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/c3d9ee37-67f5-462f-be5f-190b18c01fbc)

**Comment by aaaaargZombies** [comment]
## Verified

There was a design change but the functionality is there

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/7aa5a7bb-0b90-4b1b-98eb-034a20b0457e)
