### ISSUE TITLE
[Bug]: Video styles broken

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#182]
## What happened?

View a guide with a video - the video overlapped other content and was small.

## What were you expecting to happen?

See a video not overlapping other content & full width

## Steps to reproduce
![image](https://user-images.githubusercontent.com/861172/234543114-1ac12481-2549-4d1e-b034-3677d45b8349.png)

## Platform (if relevant)

What device and browser were you using?

**Comment by ivan-kocienski-gfsc** [comment]
I think this is because the image is not being constrained to the width of the column and it is overflowing

**Comment by katjam** [comment]
Verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/e2b01fcb-d757-47b6-bd69-bf2963d8b935)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/aa5495b1-0f30-4cdd-90cf-8b80ef5d5e72)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/7b6e5aed-aa61-4a5b-ac0c-07d591286399)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/023c0103-5927-40c1-affa-027b191f10d7)
