### ISSUE TITLE
Guides have categories for themes/subjects

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#193]
## Acceptance Criteria

- [ ] A user can apply a tag in the cms (but they do not necessarilky have to be able to apply a welsh tag)
- [ ] Tags are translated into welsh in the site when viewing in welsh

## Implementation plan

- Need to consider how best to deal with translating the tags - it might be simplest to put the key in the CMS and make it not translateable
- Then hard code the translations into a dictionary in elm
- Make a note in the CMS that welsh is translated in the site
- Make the cms list of tags a picklist, only allow application of one per guide
- Add one more tag for actions? Ask autumn

## Tags

Grwpiau Cymunedol – Gweinyddol a Gwybodaeth / Community Groups – Admin and Information

Cyfryngau, Cyhoeddusrwydd a Digwyddiadau / Media, Publicity and Events

Gweithio gyda Phobl / Working with People

Gweithio gyda'r Awdurdodau / Working with the Authorities

**Comment by katjam** [comment]
Here is what we have at the moment. In Welsh and English! Four categories/themes/subjects/whatever they are. I think they are best described as categories?

Grwpiau Cymunedol – Gweinyddol a Gwybodaeth / Community Groups – Admin and Information
[Mathau o Grwpiau Cymunedol (Cymru a Lloegr)](https://www.wildlifetrusts.org/sites/default/files/2022-10/TypesOfGroup_TRANS_CYM.pdf) / [Types of community group](https://www.wildlifetrusts.org/sites/default/files/2022-10/TypesOfGroup_CYM.pdf)
[Sefydlu grŵp cymunedolsylfaenol ](https://www.wildlifetrusts.org/sites/default/files/2022-10/SettingUpACommunityGroup_TRANS_CYM.pdf)/ [Setting up a community group](https://www.wildlifetrusts.org/sites/default/files/2022-10/SettingUpCommunityGroup_B_CYM.pdf)
[A ddylai ein grŵp ni gael cyfansoddiad?](https://www.wildlifetrusts.org/sites/default/files/2023-01/ConstitutedGroups_TRANS_CYM.pdf) / [What is a constituted group?](https://www.wildlifetrusts.org/sites/default/files/2022-11/ConstitutedGroups_CYM.pdf)
[Cyfrifon Banc ar gyfer Grwpiau](https://www.wildlifetrusts.org/sites/default/files/2022-10/BankAccountsForGroups_TRANS_CYM.pdf) / [Bank accounts for groups](https://www.wildlifetrusts.org/sites/default/files/2022-10/BankAccountsForGroups_CYM.pdf)
[Yswiriant ar gyfer grwpiau lleol](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowAreLocalGroupsInsured_TRANS_CYM.pdf) / [How are local groups insured?](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowAreLocalGroupsInsured_CYM.pdf)
[Asesiadau Risg](https://www.wildlifetrusts.org/sites/default/files/2022-10/RiskAssessments_TRANS_CYM.pdf) / [Basic risk assessments](https://www.wildlifetrusts.org/sites/default/files/2022-10/RiskAssessments_CYM.pdf)
[Dod o Hyd i Gyllid](https://www.wildlifetrusts.org/sites/default/files/2022-10/FindingFunding_TRANS_CYM.pdf) / [Finding funding](https://www.wildlifetrusts.org/sites/default/files/2022-10/FindingFunding_CYM.pdf)
[Sut i Wneud Cais am Gyllid](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToApplyForFunding_TRANS_CYM.pdf) / [How to apply for funding](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToApplyForFunding_CYM.pdf)
[How to recruit a Community Organiser ](https://www.wildlifetrusts.org/sites/default/files/2023-02/Guide-to-Recruiting-a-Community-Organisers_FV.pdf)- detailed information from NACO (English only at this stage)
Cyfryngau, Cyhoeddusrwydd a Digwyddiadau / Media, Publicity and Events
[Sut i Gynnal Digwyddiad Codi Arian](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToRunAFundraisingEvent_TRANS_CYM.pdf) / [How to run a fundraising event](https://www.wildlifetrusts.org/sites/default/files/2022-10/HowToRunAFundraisingEvent_CYM.pdf)
[Datganiadau i'r Wasg – cyfarwyddyd](https://www.wildlifetrusts.org/sites/default/files/2023-01/PUBLICPressReleaseGuidance_TRANS_CYM.pdf) / [How to write a press release](https://www.wildlifetrusts.org/sites/default/files/2022-10/PUBLICPressReleaseGuidance_CYM.pdf)
Gweithio gyda Phobl / Working with People
[Ymgysylltu cymunedol amlieithog](https://www.wildlifetrusts.org/sites/default/files/2022-10/MultilingualCommunityEngagement_TRANS_CYM.pdf) / [Working with many languages](https://www.wildlifetrusts.org/sites/default/files/2022-10/MultilingualCommunityEngagement_CYM.pdf)
[Cynghorion Ymarferol ar gyfer Cyfathrebu Traws-ddiwylliannol ](https://www.wildlifetrusts.org/sites/default/files/2023-01/PracticalTipsCrossCulturalCommunication_TRANS_CYM.pdf)/ [Cross-cultural communication](https://www.wildlifetrusts.org/sites/default/files/2022-11/PracticalTipsCrossCulturalCommunication_CYM_rev2.pdf)
[Sicrhau bod pawb yn gallu cael mynediad at eich grŵp neu brosiect](https://www.wildlifetrusts.org/sites/default/files/2023-01/EnsuringAccessibility_TRANS_CYM.pdf) / [Making sure everything is accessible](https://www.wildlifetrusts.org/sites/default/files/2022-11/EnsuringAccessibility_CYM.pdf)
[Rheoli gwrthdaro mewn grŵp](https://www.wildlifetrusts.org/sites/default/files/2023-01/ManagingConflict_TRANS_CYM.pdf) / [Managing conflict in a group](https://www.wildlifetrusts.org/sites/default/files/2023-01/ManagingConflict_CYM.pdf)
Gweithio gyda'r Awdurdodau / Working with the Authorities
[Rheoli gofod gwyrdd yn eich ardal ](https://www.wildlifetrusts.org/sites/default/files/2023-01/TakingOverGreenSpace_TRANS_CYM.pdf)/ [Taking over green space](https://www.wildlifetrusts.org/sites/default/files/2022-10/TakingOverGreenSpace_CYM.pdf)
[Sut i gysylltu â'ch AS](https://www.wildlifetrusts.org/sites/default/files/2022-10/ContactYourMP_TRANS_CYM.pdf) / [How to contact your MP](https://www.wildlifetrusts.org/sites/default/files/2022-10/ContactYourMP_CYM.pdf)
[Beth mae cynghorau ac awdurdodau lleol yn ei wneud?](https://www.wildlifetrusts.org/sites/default/files/2023-01/AboutCouncilsAndLAs_TRANS_CYM.pdf) / [All about councils and local authorities](https://www.wildlifetrusts.org/sites/default/files/2022-10/AboutCouncilsAndLAs_CYM.pdf)
[Siarad â Chynghorau, Cynghorwyr a Phobl mewn Awdurdod](https://www.wildlifetrusts.org/sites/default/files/2023-01/SpeakingToCouncils_TRANS_CYM.pdf) / [Speaking to councils with confidence - practical tips](https://www.wildlifetrusts.org/sites/default/files/2022-11/SpeakingToCouncils_CYM.pdf)

**Comment by katjam** [comment]
Research:

How to deal with translatable tags that are also used for sorting / filtering content.

**Comment by ivan-kocienski-gfsc** [comment]
I am using slugs in the CMS backend so the category selection looks like:

![Screenshot_20230607_130753](https://github.com/geeksforsocialchange/teamwilder/assets/109223824/99ac96ef-bba0-4c41-bc13-ad486b3ad9af)

**Comment by aaaaargZombies** [comment]
## Verified

A user can apply a tag in the cms (but they do not necessarilky have to be able to apply a welsh tag)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/9b88cf8d-9bc7-405d-8497-56fe43286916)

Tags are translated into welsh in the site when viewing in welsh

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/f9532060-efa8-4ab8-9c8a-26c797f75d95)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/1566ea95-5e41-4d5c-895b-083a6268148a)
