### ISSUE TITLE
[Bug]: Design bugs following Beta v1

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#203]
## Description
These things were flagged by Emma pre-sprint and also in design sweep the end of sprint: https://www.notion.so/gfsc/TeamWilder-design-sweep-f88a5f22479c43fb958751b576d0eda8

- [x] #439
- [x] #440
- [ ] #441
- [ ] https://github.com/geeksforsocialchange/teamwilder/issues/431
- [x] #438
- [ ] #211

### Done

- [x] #210
- [x] #209
- [x] #433
- [x] URGENT: Video is a bit small? Can it be full column width? In progress #184 

### Does this need to be done?

- [ ] #454

**Comment by undividual** [comment]
Design for a 'contents page' below — note, 6 columns not 7, space for short intro sentence, and titles in bold purple with arrow. 
![MVPWireframes_5](https://user-images.githubusercontent.com/90701712/236449454-a3f0c190-31c7-4cf6-bd9c-6dfa588f5dce.jpg)

**Comment by r-ferrier** [comment]
closing as all issues now opened elsewhere
