### ISSUE TITLE
Set up elm-review

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#21]
## Description
Set up elm-review to run on build?

## Plan
- [ ]

**Comment by aaaaargZombies** [comment]
should this be a pre-commit hook or something I'm a bit weary of adding more stuff to the build command given cloudflares behavior. I'm also not sure how often we'll read the output of it there.

**Comment by r-ferrier** [comment]
We do have elm review BUT we never actually set it up to happen automatically - what was the reasoning for this or is it just an oversight? Can't find any info in the related PR other than the above warning that it wouldn't be great on cloudflare.

**Comment by katjam** [comment]
We could think about it. In a mature project it can be good. But in our case right now, it's probably mmorecofca roadblock. I think we can keep running it manually and maybe add that to the readme.

The issu is basically there are some things we don't want to block from interim releases.

**Comment by katjam** [comment]
I removed question tag. We should probably not add this as an auto on build - because it can be an annoying blocker. We should add to pre-release checklist to do a review at the end (and people can run throughout as they add code)

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/f1d2d5e1-d58f-4ba1-a9bc-eeed298c0a27)
