### ISSUE TITLE
[Bug]:  feature images too large / overflow

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#216]
## Description

Feature images in stories (and probably guides) are taking up more space than they think they are when only two columns exist.

![Screenshot 2023-05-04 at 09 30 51](https://user-images.githubusercontent.com/46496391/236151993-d24cd689-8d57-44bc-8ec9-dcd7887481fd.png)

**Comment by katjam** [comment]
duplicate of #260
