### ISSUE TITLE
Update design of guide page to include image as per wireframe

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/teamwilder#217]
## Description

The guide page now includes space in the design for an image (every guide will have one — will be the same as the thumbnail image shown on homepage or guide index page, e.g. hedgehog)

Basically, the guides now have a new 'header' section which includes title of guide (big), short intro copy (this has moved from the top of the text guide to act as a general introduction to the page), image, image credit, and link back to previous page. 

As the intro copy has moved, the 'text guide' now expicitly says 'text guide' next to the icon.

Also note while updating this page that 'Experience' has changed to 'your story' in the case study promo box bottom right.

When downsizing to tablet or mobile, content priority order should be:
Main title
Image
Image credit
Intro copy
Link back to previous page

## Plan

- [ ] Step one to achieve this

## Acceptance criteria

- [ ] ~~There is now a header section which contains title, image, intro copy, image credit~~
- [x] There is now a header section which contains title
- [x] This content sensibly restructures across different views according to priority order above
- [ ] All of this content can be poulated in the CMS
- [x] There is a line dividing the header summary, image, credit from the rest of the content
- [x] The featured image has curvy corners
- [x] The image credit is prepended by: "Image credit: "
- [ ] #318
- [ ] #319
- [ ] #328
- [ ] #278 (see discussion on content in comment below)

![MVPWireframes_2](https://user-images.githubusercontent.com/90701712/236482540-2b30188e-38e0-4156-b79f-a6d45993d54a.jpg)

**Comment by katjam** [comment]
For reference - currently looks like:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/11943fc1-d07e-476a-babb-f406ee2c9a70)

**Comment by undividual** [comment]
Yes, I do think it needs to say 'image credit:' so it's totally clear what this is.

**Comment by r-ferrier** [comment]
@undividual how should this look now if we don't have a summary any more?

**Comment by r-ferrier** [comment]
have made these changes in feat/217-update-guide-page but am leaving until we have resolved what to do with summary before making a PR

**Comment by undividual** [comment]
@r-ferrier see attached wireframe. Also note I have added a breadcrumb here — I am aware it may be hard/too late to add this, but Autumn suggested it as an alternative to 'return to previous page' link (which I have also removed). However I am aware this may be too complex to implement at this stage so we may ignore. 
![MVPWireframes_2](https://github.com/geeksforsocialchange/teamwilder/assets/90701712/1ba26a4b-de96-45fe-96bf-0fd2c0392b6d)

**Comment by r-ferrier** [comment]
@undividual I think some variation on this would be fine but I don't know how much time we have for it, so if it's alright with you I'm going to make this into a new issue to put into the backlog

**Comment by undividual** [comment]
Yes, totally fine @r-ferrier! So for now just leave that out but the rest of the design should give the guidance you need for this issue.

**Comment by r-ferrier** [comment]
@undividual This section - now that we know there is no relationship between guides and stories, should this just be a selection of randomly suggested stories with some generic copy applied to every guide?

![Screenshot 2023-06-06 at 13 18 03](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/4a381a1b-cc29-44bc-b2f1-a37ee04ba922)

**Comment by r-ferrier** [comment]
And what should this be saying here? Is there some generic copy we can apply to every guide?

![Screenshot 2023-06-06 at 13 19 39](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/826119c0-96bc-41ac-8f36-18ced8367947)

**Comment by r-ferrier** [comment]
@undividual  Do we have a list of what this content should be anywhere?

![Screenshot 2023-06-06 at 13 20 42](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/19aba4ce-f2ad-48dc-8ec8-3319fb8e5487)

**Comment by r-ferrier** [comment]
I've removed myself from this, have done some of the work, sharded out the rest and put in two more AC which need confirming before this is ready to be worked on again. Once decided we can split out these into separate cards and close this issue but leaving here for now while the conversation is all happening here.

**Comment by katjam** [comment]
@undividual We have clarified with Autumn that Guides do not have any relation to Stories - ever. So I think we should remove that section.

It's a blow in terms of the purpose of this vehicle, but at this stage, we probably don't have a way forward with it. It seems like maybe it was a fundamental misunderstanding, but good that we are talking through it now.

**Comment by katjam** [comment]
Closing as other issues have been raised intead.

**Comment by r-ferrier** [comment]
Verified at desktop, tablet & mobile

<img width="1442" alt="Screenshot 2023-06-21 at 12 02 20" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/8fd34fb9-7f99-4369-b648-e8a3d39c6866">
<img width="491" alt="Screenshot 2023-06-21 at 12 02 34" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/ada00635-32a9-4af9-a085-3473d5aab03b">
<img width="494" alt="Screenshot 2023-06-21 at 12 02 51" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/d715ebe9-c94e-4b98-94c2-75bc1d8b740e">
