### ISSUE TITLE
Change of the way we talk about 'case studies' and 'experiences'

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/teamwilder#218]
## Description
Language has changed around how we talk about case studies.

## Acceptance Criteria
- [ ] The 'submit your case study' form should now read 'Share your story' as the main title
- [ ] Case studies pages themselves should be titled 'Real life story' not 'Case Study'
- [ ] #278

Wireframes have been updated on Miro to reflect this. 
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/255dd2ac-ab50-4a6d-9cab-e6d67849a63f)

**Comment by katjam** [comment]
Done
