### ISSUE TITLE
Make design of 'guides/search' page reflect newly made wireframe

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/teamwilder#219]
## Description

As referenced in #203 I have now created a design for the 'contents' page. This would be a page for the full A-Z of all guides, and also pages for smaller subsets of guides (e.g what you get when you click 'Get connected' or any of the other 'gets' on the homepage). Design as per below. 

## Acceptance criteria

- [x] Guides display in max 6 columns at desktop view 
- [x] Each guide has an image space (square)
- [x] Each guide has a clickable title, styled as per wireframe
- [x] Each guide has a short sentence of intro copy
- [ ] #325
- [x] Make sure guide teasers have consistent sizing - see comment at bottom of #145

![MVPWireframes_5](https://user-images.githubusercontent.com/90701712/236485409-6762a265-258d-4fa2-894e-264ad5fdccfc.jpg)

**Comment by r-ferrier** [comment]
Broadly works well, one nice to have query on the search title!

<img width="369" alt="Screenshot 2023-06-21 at 12 07 58" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/30783c1c-635b-47c1-af3e-dc7cf693c474">
<img width="615" alt="Screenshot 2023-06-21 at 12 07 51" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/fed46bc3-452d-4bfc-8039-ffde069179db">
<img width="874" alt="Screenshot 2023-06-21 at 12 07 44" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/217836d2-6136-4414-90f8-4468ec287ebb">
<img width="1017" alt="Screenshot 2023-06-21 at 12 07 38" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/102c8723-fea6-407b-a0b9-3d301e7b93e6">
