### ISSUE TITLE
Update design of homepage to reflect revised wireframe

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/teamwilder#220]
## Description

Some small changes to the homepage design

## Acceptance Criteria
- [x] There is no more key to icons
- [x] No more icons included under guides
- [x] "Welcome to the nextdoor nature library" is big (to match main titles on other pages) and spans width of page

![MVPWireframes_](https://user-images.githubusercontent.com/90701712/236486564-c1eedf60-bf40-4623-8565-9d6174b01e53.jpg)

**Comment by r-ferrier** [comment]
Design is verified.

<img width="974" alt="Screenshot 2023-06-21 at 11 25 02" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/759e30f8-b418-466f-bd1c-a8b7b04bdf57">

The title now says `welcome to this nextdoor nature hub` which implies to me it's one of many - should this be `welcome to the nextdoor nature hub`? Question for @AutumnBarlow

**Comment by AutumnBarlow** [comment]
Good point, I had changed it to "this" in a brain fart moment. I will change it back.

**Comment by r-ferrier** [comment]
> Good point, I had changed it to "this" in a brain fart moment. I will change it back.
> 
> Update, I guess you folks are doing stuff as I cannot change it: getting this error Failed to persist entry: API_ERROR: Validation Failed

@AutumnBarlow ah brill! We've spotted your change and merged it in - not sure why that was happening but it came through fine.
