### ISSUE TITLE
[Bug]: Tests failing & not running during deploy pipeline

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#223]
## Description

Tests should be running automatically some point in our pipeline. Probably on Pull Request creation as suggested in #3 

As part of this - run `elm-review` to tidy up the code.

**Comment by aaaaargZombies** [comment]
## verified

https://github.com/geeksforsocialchange/teamwilder/blob/main/.husky/pre-push
![2023-06-21-11:53:33-screenshot](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/8ff4a03c-4af5-46cd-9ca0-d3b18babb55a)
