### ISSUE TITLE
[Bug]: Should not be able to generate new pages using CMS

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#251]
## Description

Add a page that isn't defined in our codebase (currently About & Privacy Policy)

## Steps to reproduce

1. The CMS should not allow editors to add pages that don;t exist in the app
2. 
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/36901c6c-747a-41f5-a79b-162ba2d2dfb3)

## Platform (if relevant)

What device and browser were you using?

## Dev Notes

- Using Netlify CMS/Decap CMS.
- The config file lives in `public/admin`
- It's the [create attribute](https://decapcms.org/docs/configuration-options/#collections)

**Comment by katjam** [comment]
I think there is a config for "cannot create new ones" - so it should be a single line of code. If this is not a single `e` then it is not as important. Nothing bad will happen if someone adds a page, but it could cause false expectation.

**Comment by ivan-kocienski-gfsc** [comment]
Is there a config file for this or is it on the CMS site? Nothing obvious is popping up for me

**Comment by katjam** [comment]
Yes. It's the `create` attribute here:

https://decapcms.org/docs/configuration-options/#collections

**Comment by r-ferrier** [comment]
And the config file lives in `public/admin`
