### ISSUE TITLE
Guides and stories have a summary

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#252]
## Acceptance criteria

- [x] A story has an optional summary field that is not rendered in the view
- [x] A story uses the summary text as meta description - with fallback to "A story about [Who]: [Title]" copy TBC
- [x]  A guide has an intro section at top of guide next to the image (as per original design)
- [x] A guide shows summary text in the teaser
- [x] A guide uses the summary (intro) as it's SEO description

###  Implementation notes & questions

The `summary` field is currently used in SEO description, teaser & at the top of a guide.
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/2ba378c3-0c8d-4227-ba75-1bb497bfe712)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/00366a86-0520-4442-a200-57b4f0885239)

Autumn:
Can we make the “summary” part of the guides invisible? Happy for it to exist to feed into metadata but I am finding it doesn’t work mostly because I have no idea what to put in the Welsh side of things so I end up copying the first sentence of the Welsh text and then the repetition looks a bit daft on the page.

Katja:
Yes! I can remove the summary. :) Sorry I misread invisible as visible. I'll raise an issue to talk about it also because I think it was intended as a "short description" that would be an ata glance version which is protentially a useful feature - but no good if you don't have copy ready for it.

**Comment by r-ferrier** [comment]
In the morning meeting it was discussed that summaries are not generally any different to the first few lines of content and there are no welsh translations for new summaries, so it was preferred to not have them and to instead use the first few lines of content for any situation where summary was required for presentation purposes (ie the teasers)

**Comment by katjam** [comment]
Can I suggest that if we always want to use the first few lines as summary. We keep the seperate field because that ensures we have complete sentences for SEO description and teaser. 

This also will enforce that all guides (and stories) have the same structure and provides better usability+ an at a glance consistent section at the start.

So @AutumnBarlow will enter the content in 2 boxes (intro + main body). We make sure we search on both.

**Comment by r-ferrier** [comment]
@katjam Ok, I'll update my current PR to leave the CMS content as is. 

At the last meeting I was at it sounded like the issue with subtitles is that we don't have any in welsh or intent to provide them in welsh, so we would need to continue to pull the welsh from the content. How about I pull a summary in when a summary exists and fall back to preview when it doesn't?

**Comment by katjam** [comment]
Maybe that's a good solution but I think we still want to normalise so we can explain to Autumn interns of structuring the content. In terms of what she already has in Welsh & English as far as intro text it's fine to keep and split put the intro from the main text manually. There is no point undoing that design and separation if we're just going to guess by cutting the first 50 words from top of body. We may as well be thoughtful about it.

**Comment by katjam** [comment]
@undividual Can you confirm that we want to design the pages as per the images above?

**Comment by undividual** [comment]
If they are to include summaries, then yes, they are the designs.

If no, this was my revised version (which also included breadcrumb, which I know is in backlog)
It's a shame as I actually kind of prefer the new version but it doesn't work with summaries included (the first column gets too long before you get to 'actual content'

![MVPWireframes_2](https://github.com/geeksforsocialchange/teamwilder/assets/90701712/0e3356af-d823-4f0e-930c-7c834187b3db)

**Comment by aaaaargZombies** [comment]
## verified

 A story has an optional summary field that is not rendered in the view (after discussion this was made non-optional)
 
![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/0d3d3720-a802-46cd-88b4-6af227bb79a0)


A guide has an intro section at top of guide next to the image (as per original design)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/d0cb45c0-0437-4492-8016-5777b268c01f)


A guide shows summary text in the teaser


![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/82256a3e-9bd4-4881-a121-c57cb705320b)


## Issues

A story uses the summary text as meta description - with fallback to "A story about [Who]: [Title]" copy TBCV

https://socialsharepreview.com/?url=https://team-wilder-proto.pages.dev/guides/all-about-councils-and-local-authorities

A guide uses the summary (intro) as it's SEO description

**Comment by katjam** [comment]
@aaaaargZombies the image missing is due to the url, but the description should be the js injected one. I think sometimes, it might not work because requires js to run... but mostly it does these days. There is nothing we can do unless we move to static html pages.
