### ISSUE TITLE
[Bug]: Broken stories redirect to home page but with broken url remaining

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#253]
## Description

Visiting https://team-wilder-proto.pages.dev/story/broken-link takes you to the home page

It should probably either take you to a 'story does not exist' page like a broken guide does, or to the home page but without the extra url info, depending on what we want behaviour to be here

A dev conversation to decided which approach is best given remaining time etc needs to happen

## Acceptance criteria

Either
- [x] guides and stories have a 404 page that displays when you are on the wrong url

**Comment by r-ferrier** [comment]
@undividual to provide design

**Comment by undividual** [comment]
After discussion with Autumn (I am just awaiting her confirmation that she likes the illustration, but the page will basically look like this, so feel free to build accordingly, we may just swap the illustration if she doesn't like it!):

![MVPWireframes_6](https://github.com/geeksforsocialchange/teamwilder/assets/90701712/fbd9583f-3be9-4b55-8176-9c262d29b80c)

Illustration here:
![Untitled_Artwork](https://github.com/geeksforsocialchange/teamwilder/assets/90701712/f747c3da-2401-4782-b4c0-a7f34cd2b323)

**Comment by r-ferrier** [comment]
This does work, but the image is really big and so the page takes up a lot more space than is probably ideal - would be better if it was constrained a bit more so the footer is visible
