### ISSUE TITLE
I can tell which link I am currently on by looking at the footer (or elsewhere?)

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#254]
## Acceptance criteria

- [ ] Nav links are underlined when I hover over them
- [ ] The active page nav link is underlined

## Dev notes

In the footer module, pull out the global model and "read" the navigation key to determine where the user currently is. Then render the links giving them an active style (TBC) when browser is on that page.

**Comment by undividual** [comment]
Good point — for now, could it be as simple as adding an underline on rollover? This is probably what I would design but I doubt you even need to see a visual of this! (Let me know if you do though)

**Comment by ivan-kocienski-gfsc** [comment]
Would it not be clearer to have the nav state display in a more prominent position in or below the header?

By the time the user has reached the footer they have already seen all the content.

**Comment by aaaaargZombies** [comment]
## Verififed

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/f9c8ac29-a95f-4000-a485-6049580dac15)

There is a difference but it is quite subtle

**Comment by undividual** [comment]
Oh sorry, some wires crossed here. This doesn't work.
Underlines should always be the thinner version. Could we either do:
Type goes bolder
OR
Type becomes teal
OR
You mentioned another site does a kind of, highlight behinf feature? 

What do you think would work best? (cc @katjam )

**Comment by aaaaargZombies** [comment]
I've opened an issue here #508
