### ISSUE TITLE
The homepage content is as intended

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#256]
## User story

Currently the stuff on the homepage is a little arbitrary and contains placeholders

## Acceptance criteria

- [x] The 4 "featured" guides on the homepage  become "guide highlights" and "story highlights"
- [x] Highlighted guides and stories are assigned randomly
- [x] Number of stories & guides limited to two of each
- [x] #220 
- [ ] #178 
- [ ] #145

**Comment by katjam** [comment]
### Question:

Refer to the design and make decisions about what we want and how it is curated.

**Comment by katjam** [comment]
@undividual Can you make a first pass at what needs to stay here and what needs to go in terms of content? Maybe with a chat with dev to hear how hard stuff is to do.

**Comment by undividual** [comment]
Hey @r-ferrier @aaaaargZombies @ivan-kocienski-gfsc based on @katjam's comment above I would value 10-15 minutes on a call with one of you to help better define this stuff as I am struggling to parse it from here!

**Comment by ivan-kocienski-gfsc** [comment]
Are we (@r-ferrier @aaaaargZombies) having a meeting on Monday to bring Alfie up to speed on the milestone. @undividual may want to jump into that for a group chat.

**Comment by katjam** [comment]
@ivan-kocienski-gfsc Stuff with question label isn't ready to be worked on.

**Comment by r-ferrier** [comment]
verified - refreshing the page generates a new random selection of guides & stories, two of each.
