### ISSUE TITLE
review CMS content and make sure there are Welsh translations

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/teamwilder#257]
## Description / Acceptance Criteria

- [ ] Make sure there are English and Welsh translations of ancillary pages

## Development Notes

| Page | English | Welsh |
|--|--|--|
| Index | | |
| About | | |
| Privacy Policy | | |
| How to use this site | | |
| Submit Story | | |

**Comment by katjam** [comment]
@AutumnBarlow The [ccc] in the Welsh copy that needs fixing in the CMS by you is in the Welsh of How to use this Site page and the title of Share Story page as you pointed out.

I suspect you'll be finding these on your travels today.

The rest of the [cCc] are in the code copy and I'll be fixing them with #109

Can you close this issues once you've removed the placeholders from those 2 CMS pages?

**Comment by AutumnBarlow** [comment]
Closing - Share your Story and How to Use this Site are now in Welsh.
