### ISSUE TITLE
Add logo and short about text to the footer

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#26]
## User story
As a person discovering the site I need to know who is behind the site so that I can trust the information.

## Acceptance criteria
- [x] I can see a logo in the footer
- [x] I can see some information about the project in the footer

## Implementation notes & questions
Probably worth adding the responsive layout for footer "columns" with this if that hasn't been done in #27

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/223695535-04003a09-675d-4974-bdf5-631d8e261b04.png)

**Comment by r-ferrier** [comment]
verified

![Screenshot 2023-05-29 at 15 02 41](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/8c33c8a9-8f74-4057-99c3-9c47773c8bfa)
