### ISSUE TITLE
Footer partner logos change based on language

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/teamwilder#261]
As a follow on from #108 

## User story

As a proud Welsh speaker, when I change language I want to see ALL the logos change language as well

## Acceptance criteria

- [ ] language of logos in footer change when I select my preferred language

## Prerequisites

- [ ] logo graphics as SVGs in Welsh

**Comment by katjam** [comment]
won't fix and duplicate of #146
