### ISSUE TITLE
[Bug]:  css reset is not being loaded

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/teamwilder#263]
## Description

I was forking teamwilder repo to make a elm-starter, after deleting most of the content I noticed the reset wasn't being applied.

It looks like we're importing the css as a string but not doing anything with it

https://github.com/geeksforsocialchange/teamwilder/blob/main/src/js/index.js#L1

https://vitejs.dev/guide/features.html#disabling-css-injection-into-the-page

## Steps to reproduce

1. What you did first
1. What you did next

## Platform (if relevant)

What device and browser were you using?

**Comment by katjam** [comment]
Great catch! I even verified that issue yesterday. Oops.

**Comment by r-ferrier** [comment]
reset is loaded 
<img width="401" alt="Screenshot 2023-06-21 at 11 22 43" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/cd770047-bef0-412e-b882-8be1ffb44953">
