### ISSUE TITLE
[Bug]: Search bar layout is doing strange things at smaller sizes - think this is because of label that needs removing

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#264]
## Description

Here's how the search bar looks at a smaller size currently:
<img width="526" alt="Screenshot 2023-05-30 at 09 42 27" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/fd1d74d2-2be9-4503-a05a-289fb9df4af7">

here's how it looks if we remove the label:
<img width="356" alt="Screenshot 2023-05-30 at 09 42 51" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/fff8f814-afc6-4cdd-9b58-6ff82a448d14">

**Comment by katjam** [comment]
#165
