### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#275]
## Description
Run down accessibility checklist to make sure we're doing all the right things. Obviously we will be accessibility first as we build but it's worthwhile to do an audit after we have built a few pages.

### Must do: 
- [x] Run something like lighthouse (https://developer.chrome.com/docs/lighthouse/overview/)
- [x] Use a WAVE tool to evaluate each page type  https://wave.webaim.org/
- [x] Run through site use with keyboard only
- [x] Check all meaningful images for alt text
- [x] Check all form inputs for labels
- [x] Check all links for meaningful & unique link text
- [x] Check all headings are correct for their semantic meaning

## Notes
- Starling bank has a nice statement https://www.starlingbank.com/website-accessibility. We ought to be doing all the things listed there as "What we are doing"

## Dev plan (issues picked up when running all checks on 31st May)

keyboard only use
- [x] Implement scroll to top to refocus on correct element when visiting linked pages

Links
- [x] Cookie buttons? I think they're ok because of the context of the text preceding them but in isolation mean nothing

## Dev plan (additional issues picked up when running all checks on 20th Jun)
lighthouse recommendations
- [x] Image optimisation - currently serving full size images on all pages
- [x] Font optimisation - we're still loading fonts from the google & adobe CDNs - didn't we decide against this?
- [ ] #466

wave recommendations
- [ ] #465
- [x] no alt text on icon images - add, or maybe better to hide from screenreaders? (the span containing the icon is aria-hidden already)
- [x] add alt text to footer logos
- [ ] empty heading on search page when no search text entered - should only be rendered if text exists
- [x] skipped heading level on stories - goes straight from h1 to h3 - who & where should be h2 if poss

## A final thought!
- [x] #464

**Comment by r-ferrier** [comment]
Moving this to pre-release checks as many of these covered in other tickets & we need to re-sweep after generating new features

**Comment by r-ferrier** [comment]
wave screenshot from our site & the wildlife trusts for wales site showing page language

<img width="1103" alt="Screenshot 2023-06-20 at 09 56 04" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/099551b4-820f-4220-a2b8-5c488d26fe98">

<img width="423" alt="Screenshot 2023-06-20 at 09 57 20" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/9f42fdfc-97a2-4e2d-9c0b-f1db52718fc1">

**Comment by katjam** [comment]
Done.
