### ISSUE TITLE
[Bug]: Do we need to stop husky from trying to edit CMS markdown files? 

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#280]
## Description

Husky wants to commit changes to markdown - is there any risk of it making things more confusing for cms users if we allow this? Should we just have it ignore these files?

## Steps to reproduce

1. What you did first
1. What you did next

## Platform (if relevant)

What device and browser were you using?

**Comment by katjam** [comment]
Good call. Let's ignore them.
