### ISSUE TITLE
Add Intro to project text to index

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#29]
## User story
As a person visiting the site, I need to see some explanation of the core mission of act, connect, share so that I know what this is all about and can take part meaningfully.

## Acceptance criteria
- [x] There is some intro text on the index  page
- [x] I can see a `[cCc]` at the start of this text so I know it needs to be approved

## Implementation notes & questions

The text should be put in the Copy module. Later on we will want to pull this from markdown

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/223705798-3cc7fb38-305d-41d2-bf27-a7a6fc9d2755.png)

**Comment by r-ferrier** [comment]
This is existing but with [cCc] which I think is fine for now because it means it will be reviewed later.
