### ISSUE TITLE
[Bug]: CMS upload images paths not resolving

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#301]
## Description
 Path to image is incorrect in build

**Comment by katjam** [comment]
@AutumnBarlow I noticed you started adding images - which is great! But it's shown up an issue that they are not being found. I am looking to fix that!

**Comment by katjam** [comment]
We can batch process the ones that are there, and then we'll come up with an optimum size as a guide for you and add it to the upload field as a reminder (and maybe a limit). #302

**Comment by r-ferrier** [comment]
verified - Image paths are now all resolving correctly on live and none in contents or keys point to /public
