### ISSUE TITLE
Uploaded images can be huge

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#302]
## Acceptance criteria

- [ ] Message near image upload input box describing the constraint
- [ ] All mages are ~1MB

## Implementation notes & questions
- We might want to restrict, treat or add guidelines
- As a minimum, we should process existing images (in uploads) to be a smaller size.
- Once we decide what best size / ratio is, let Autumn now as well as putting guide and or limits in the CMS interface

**Comment by katjam** [comment]
Leaving in no milestone for triage.

**Comment by katjam** [comment]
My plan was 1 batch process all existing images. 2 add hint text to remind Autumn to keep them under ~1mb.

The site will not break if she doesn't follow. It will just be slow to load.

**Comment by katjam** [comment]
So we don't need any special support from decap. All it does is copy the image to GitHub as far as I know we can't limit size or process automatically without a further service integration which we don't plan to do.

**Comment by ivan-kocienski-gfsc** [comment]
Can this be tested on localhost or will it try to push images to the live repo?

**Comment by ivan-kocienski-gfsc** [comment]
digging around i found a few people who really [wanted this functionality](https://github.com/decaporg/decap-cms/issues/1322) from 2018 or so. 

seems like there is a config that can be defined along the lines of
```yaml
 media_library:
   name: TW media library
   config:
     maxFileSize: 50000 # five megabytes
```
see [media_library config](https://decapcms.org/docs/configuration-options/#media-library).

This is as far as I got down the rabbit hole. Leaving here for the next brave adventurer.

**Comment by katjam** [comment]
Sounds perfect

**Comment by katjam** [comment]
> digging around i found a few people who really [wanted this functionality](https://github.com/decaporg/decap-cms/issues/1322) from 2018 or so.
> 
> seems like there is a config that can be defined along the lines of
> 
> ```yaml
>  media_library:
>    name: TW media library
>    config:
>      maxFileSize: 50000 # five megabytes
> ```
> 
> see [media_library config](https://decapcms.org/docs/configuration-options/#media-library).
> 
> This is as far as I got down the rabbit hole. Leaving here for the next brave adventurer.

T I think this is for if you use a 3rd party library / service to process, store and deliver your images. We are using github so I don't think is an option for us. It's another tie-in that we don't need & is generally a paid for service. Let's see how we get on with smaller images.

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/8e3e90f0-d556-4257-8bbf-eef134d7af9e)

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/efd2473b-f699-40b3-9e80-f0b1d7d6e7c5)

**Comment by katjam** [comment]
Needs reducing again:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/9d562340-77de-43db-8619-6c175a537ed9)
