### ISSUE TITLE
Remove API guides

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#307]
## Issue

In meeting with Autumn it was mentioned that the API guides should just be there as placeholders and are not required for the final site - we need to remove them

## Acceptance Criteria

- [ ] On root page the "Explore guides by theme" section has been removed
- [ ] Any other code that is in support of this is removed (i believe its just a view thing).

**Comment by r-ferrier** [comment]
adding question label as we should probably confirm this again before diving in

**Comment by ivan-kocienski-gfsc** [comment]
Going to do this now as it is no longer marked as `question`.

**Comment by katjam** [comment]
@ivan-kocienski-gfsc It doesn't actually need doing now. I'll ping you in discord!

**Comment by katjam** [comment]
This is now a won't fix. We are adding them to the content search as text links.
