### ISSUE TITLE
As a user I can search for guides, stories and actions

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#309]
## Issue

In the meeting today it came up that there is a desire for users to be able to search stories as well as guides. In our current implementation users can only search for guides.

## Acceptance Criteria

- [ ] When I "search the hub" using the search box, it returns results which contains guides, stories & actions
- [ ] The results text contains guides, stories and actions including links to the sections and is aria announced
- [ ] Guide and Story teasers have images, actions do not
- [ ] There is a browse stories, linked from the footer goes to stories section of search page
- [ ] There is a browse guides, linked from the footer goes to guides section of search page
- [ ] There is no separate guides or stories index
- [ ] The only way to get actions is doing the general search
- [ ] A link in the footer that takes user to the actions guides hub "Find more practical actions" in Get involved section
- [ ] search field needs a hidden label 
- [ ] #618

The implementation options we discussed were:

- Not implementing this and only searching guides. On searching guides, redirecting the user to the guides index and showing a filtered view of guide teasers.
- Implementing two index pages: a guides index and a stories index; and two search bars: a guides search and a stories search. On searching either, redirecting to the relevant index and showing a filtered view of guide or story teasers.
- Implementing three index pages: a guides index, a stories index, and a hidden index of both; and one search: an everything search. On searching, redirecting to the hidden index and showing a filtered view of guide and story teasers.

These are in what we thought would be the order of ease to implement (but probably reverse order of desirability)

## Plan

- [x] Review all occurrences of `Guides` in the code and change to `Search` if appropriate
- [x] Results for each type are kept seperate
- [x] Split results into 3 sections (Stories will be empty at first). 
- [x] Include stories in search
- [x] Add anchors to h2's so they can be scrolled to
- [x] Add links in footer to appropriate sections
- [x] #542
- [ ] #543
- [ ] Clear search on language change
- [x] get results from search
- [x] Empty state for no results
- [x] #614

**Comment by r-ferrier** [comment]
Hey @undividual @AutumnBarlow @katjam this is a summary of the search issue that has grown out of the discussion on https://github.com/geeksforsocialchange/teamwilder/issues/165 - just moving this here as it is a separate thing and you can hopefully iron out a plan for us in your next meeting as discussed this morning!

**Comment by r-ferrier** [comment]
In this morning's meeting we discussed the necessity for an index for stories as they are not linked to guides

**Comment by katjam** [comment]
We have a plan for this. I need to write it up.

**Comment by katjam** [comment]
Note from Autumn: I have begun adding a few stories and aim to have many more to upload this week. However, they are not intrinsic to any guide in particular - the stories are a huge draw to the site as we are emphasising how this is a community thing, that people can upload their own stories and discover those of others in similar situations to themselves. It may be of more use to tag and categorise the stories so that they are easy to browse.

**Comment by aaaaargZombies** [comment]
https://technology.blog.gov.uk/2014/08/14/improving-accessibility-on-gov-uk-search/

**Comment by ivan-kocienski-gfsc** [comment]
Just to note a few bugs that may get fixed when katja is done with this

- the search term dissappears if a search is done, an item is clicked and then the user navigates back
- also the title seems to display "40 guides on fox" even if searching for non-guides
- non-guides show up in "guides" search scope.

**Comment by katjam** [comment]
@r-ferrier I added a few further things to the plan. I'm struggling a bit to get results back from the search - unless I hard code them... so I'm looking into that.

I'm on a bus all day tomorrow but will try to get online a bit. I'll send Autumn a message to explain state of search when I stop.

**Comment by katjam** [comment]
Closing as ready for verify. Tasks have been sharded out.
