### ISSUE TITLE
Add actions from remote API to teaser lists

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#31]
## Acceptance Criteria

- [x] I can see actions teasers on the `/guides` page#
- [x] An actions teaser contains a title
- [x] An actions teaser contains a short description
- [x] An actions teaser links to its canonical home
- [ ] An actions teaser can be searched for (to be implemented as part of #119)

## Description
Make a plan about how we will use the actions data.

The existing JSON API for the actions content is available here: [https://www.wildlifetrusts.org/jsonapi/node/action](https://www.wildlifetrusts.org/jsonapi/node/action) 

- as discussed any reuse of this content will require canonical links to point to original pages on national site to avoid SEO penalties. 

### We need
- check external API provides data used in teaser list
- to include actions guides in our search
- provide links to the content

## Plan
- [ ] make a HTTP request and update the model
- [ ] display as part of teaser list
- [ ] link to external resource

**Comment by aaaaargZombies** [comment]
## API notes

```elm
type alias GuideTeaser =
    { title : String

    -- This will maybe turn into Url.Url when we include external resources
    , url : String
    , summary : String
    , maybeImage : Maybe Image
    }
```

```sh
curl https://www.wildlifetrusts.org/jsonapi/node/action | jq '.data[0] | {title: .attributes.title , url: .attributes.path.alias , summary: .attributes.field_action_summary.value , maybeImage: .relationships.field_action_featured_images.data[0].id }'
```

Produces

```json
{
  "title": "How to help wildlife at school",
  "url": "/actions/how-help-wildlife-school",
  "summary": "Whether feeding the birds, or sowing a wildflower patch, setting up wildlife areas in your school makes for happier, healthier and more creative children.",
  "maybeImage": "9895d2da-c6cb-4d6c-97b3-36debe148947"
}
```

`GuideTeaser.url =  "/actions/how-help-wildlife-school"` link should be `https://www.wildlifetrusts.org/actions/how-help-wildlife-school` so just need to add the website as a prefix

need to figure how to get the images, this looks useful... https://www.wildlifetrusts.org/jsonapi/media/image hopefully we can grab the images some how using the id that's shown above in `maybeImage`

```sh
curl https://www.wildlifetrusts.org/jsonapi/media/image/9895d2da-c6cb-4d6c-97b3-36debe148947 | jq '.data.relationships.field_media_image.links.related.href'
```

Produces `"https://www.wildlifetrusts.org/jsonapi/media/image/9895d2da-c6cb-4d6c-97b3-36debe148947/field_media_image?resourceVersion=id%3A4139"`

We can grab a url from that to get a banner image...

```sh
curl https://www.wildlifetrusts.org/jsonapi/media/image/9895d2da-c6cb-4d6c-97b3-36debe148947/field_media_image?resourceVersion=id%3A4139 | jq '.data.attributes.uri.url'
```

Produces `"/sites/default/files/2018-07/wildlife%40school.jpg"` if we append the base url we get https://www.wildlifetrusts.org/sites/default/files/2018-07/wildlife%40school.jpg

Which is too big they must be using some sort of processing when they make the pages based on these files....

**Comment by aaaaargZombies** [comment]
ok I think I've found the thumbnail

```sh
curl https://www.wildlifetrusts.org/jsonapi/node/action | jq '.data[0] | {title: .attributes.title , url: .attributes.path.alias , summary: .attributes.field_action_summary.value , maybeImage: .relationships.field_representative_image.data.id }' 
```

Produces

```json
{
  "title": "How to help wildlife at school",
  "url": "/actions/how-help-wildlife-school",
  "summary": "Whether feeding the birds, or sowing a wildflower patch, setting up wildlife areas in your school makes for happier, healthier and more creative children.",
  "maybeImage": "1f29650f-c1a0-4bd6-9f3c-94d1bdf3b987"
}
```

take the image id and add produce the following url

`https://www.wildlifetrusts.org/jsonapi/media/image/1f29650f-c1a0-4bd6-9f3c-94d1bdf3b987/field_media_image`

Extract the url

```sh
curl https://www.wildlifetrusts.org/jsonapi/media/image/1f29650f-c1a0-4bd6-9f3c-94d1bdf3b987/field_media_image | jq '.data.attributes.uri.url'
```

Produces

`"/sites/default/files/2018-07/wildlife%40school-2.jpg"`

**Comment by aaaaargZombies** [comment]
I may be blocked for the moment as I don't seem to be able to make a CORS request to the API

repsonse header to my request

```
HTTP/2 200 OK
cache-control: max-age=3600, public
content-language: en
content-type: application/vnd.api+json
etag: "1681896063"
expires: Sun, 19 Nov 1978 05:00:00 GMT
last-modified: Wed, 19 Apr 2023 09:21:03 GMT
permissions-policy: interest-cohort=()
server: nginx
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-drupal-cache: MISS
x-drupal-dynamic-cache: MISS
x-frame-options: SAMEORIGIN
x-generator: Drupal 9 (https://www.drupal.org)
x-pantheon-styx-hostname: styx-fe3-a-6484fbc486-h6vc7
x-styx-req-id: 81623893-de93-11ed-a928-760e3b1d6b4b
x-ua-compatible: IE=edge
date: Wed, 19 Apr 2023 09:36:37 GMT
x-served-by: cache-chi-kigq8000090-CHI, cache-lon4280-LON
x-cache: MISS, HIT
x-cache-hits: 0, 1
x-timer: S1681896997.101998,VS0,VE1
vary: Cookie
age: 930
accept-ranges: bytes
via: 1.1 varnish, 1.1 varnish
content-length: 280537
X-Firefox-Spdy: h2
```

**Comment by r-ferrier** [comment]
verified

![Screenshot 2023-05-29 at 15 50 38](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/6ffc5395-ed7f-4354-8371-a71af913a9a3)
