### ISSUE TITLE
Add Breadcrumbs under title on Guide and Story pages

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#317]
This has grown out of https://github.com/geeksforsocialchange/teamwilder/issues/306

## Acceptance Criteria

- [x] On a guide page I can see a list of breadcrumbs containing home > guides > [current page]
- [x] On a story page I can see a list of breadcrumbs containing home > stories > [current page]
- [x] home and stories and guides link to their respective indexes
- [ ] #318

![243383401-1ba26a4b-de96-45fe-96bf-0fd2c0392b6d](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/7aeace80-dc9f-41d6-a2e1-5ba2df2e8424)

**Comment by katjam** [comment]
won't fix unnecessary clutter now that we have search on all pages
