### ISSUE TITLE
On a guide page I can see a breadcrumb to a filtered view of guides by category

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#318]
## Issue

Do we want to add this / do we have time to add this - and is it a link - and where does it go and how does that page look when we get there?

![243383401-1ba26a4b-de96-45fe-96bf-0fd2c0392b6d](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/f863344f-7104-49bc-8dc3-859b3ff54aea)

**Comment by ivan-kocienski-gfsc** [comment]
We don't have a filter on the guides page so even if we did put in a breadcrumb it wouldn't be able to link to anything (?)

But once the guides are filterable it would be difficult to implement as the "show guide" page has no idea how you arrived at that page- whether you clicked on a guide in the index (unfiltered) or you had a filter applied.

we could just show a "filter category" on every guide page regardless.

**Comment by katjam** [comment]
won't fix unnecessary clutter now that we have search on all pages
