### ISSUE TITLE
formstack forwards data to email

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/teamwilder#322]
just needs to go to test account in preperation for swtiching to [nextdoornature@wildlifetrusts.org](mailto:nextdoornature@wildlifetrusts.org)

## Acceptance criteria

- [x] form data is delivered to an email account

**Comment by aaaaargZombies** [comment]
This is straightforward to set up but I can't test it from the trial account as it's limited to paid plans to prevent spam.

The defaults are what you'd want with possible exception sending photos. This is opt in at the bottom of the notification settings page.

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/a0e14de1-b581-45ba-b2ac-583beb289169)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/a30506cb-5af3-4629-9eaa-48644de1a10e)

**Comment by aaaaargZombies** [comment]
I can't verify this as we

- haven't got the form embeds
- don't have access to the email connected to the form

Hopefully @AutumnBarlow can verify this once the new forms are in place

**Comment by AutumnBarlow** [comment]
I sent the email linking out our Formstack person Andy with Alfie, copying in Katja - I don't have any details and so any questions need to be directed to Andy Rushton as per that email.
