### ISSUE TITLE
Update placeholder image

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#324]
## User story
Guides and stories will always have an image, but we want to be able to save them without so that we can source image separately to text. Therefore, it's best we have a placeholder.

## Acceptance criteria

- [x] If a story or a guide does not have an image, the placeholder shows
- [x] A story and guide can be saved without an image
- [x] The new image is used as default og:image 

## Implementation notes & questions
Autumn is providing an image.

**Comment by ivan-kocienski-gfsc** [comment]
Is there an image file? This seems blocked without it

**Comment by katjam** [comment]
Yes. Is blocked. Anything with labels "question", "cms change", "design
change" or "blocked" is likely to be blocked. I think this is quite low
down in the order anyway. Are you looking at the milestone or just issue
list? They are only in priority order in the milestone on this link:
https://github.com/geeksforsocialchange/teamwilder/milestone/5

**Comment by katjam** [comment]
![Comingsoon_orig (2)](https://github.com/geeksforsocialchange/teamwilder/assets/861172/dd23ca2e-6065-4193-9592-2f6c846887cb)

**Comment by AutumnBarlow** [comment]
![TWT_LOGO_PRIMARY_BLACK](https://github.com/geeksforsocialchange/teamwilder/assets/102548510/131931a6-80a2-44fa-ad2e-6c0d47d9f8f9)

**Comment by AutumnBarlow** [comment]
![TWT_LOGO_STACKED_BLACK](https://github.com/geeksforsocialchange/teamwilder/assets/102548510/b828db58-6f28-4e36-a386-ead5e379dec0)

**Comment by aaaaargZombies** [comment]
# Verified
 
 If a story or a guide does not have an image, the placeholder shows

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/b35bd8fe-a798-420a-b7fb-0ef98d25de21)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/208f8eb6-cd2f-4d78-b6b0-5fabc9aa4be3)


A story and guide can be saved without an image

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/1f3d5d88-abc3-4a51-8433-ac70a1078503)


The new image is used as default og:image

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/0ea012ec-1adf-4933-9181-f0c14c4e6929)
