### ISSUE TITLE
There is an appropriate privacy policy in place

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#33]
Our existing privacy policy is available here: [Privacy Policy | The Wildlife Trusts](https://www.wildlifetrusts.org/privacy-policy). For the large part this should be replicated on the Nextdoor Nature site but it should be reviewed to check it is applicable / for any omissions by the product owner (Autumn) and any amendments to the policy should be reviewed by Richard Bartlett

- [x] #116
- [ ] #117
- [ ] #118

**Comment by r-ferrier** [comment]
verified: 

![Screenshot 2023-05-29 at 16 13 42](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/7ea72316-65f9-4dcb-b4a6-ed4be28b8ca0)
