### ISSUE TITLE
[Bug]: It's unclear which url to add for YouTube embed

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#335]
## Description

Content editor needs some guidence on which url format to use for YouTube embed.

This will not be foolproof but should help as a reminder - for troubleshooting.

## Acceptance Criteria

- [ ] There is some help text on the YouTube url field showing the correct pattern
- [ ] All urls referenced in the CMS are the correct embed format

## Screenshots

Correct:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/6f248bd9-c1a8-4769-8ad4-f88509e41733)

Incorrect:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/86f752d8-960a-4791-818c-aca98171250e)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/93de40b9-ca52-462d-b818-582243cd2fee)

**Comment by katjam** [comment]
@AutumnBarlow We'll fix the existing ones - and add some help text under that field as a reminder.

**Comment by katjam** [comment]
I'm not sure if this is the easiest way to get the link but if you click the share button and then embed, you can copy this part:

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/756b3fc5-2da1-43ac-8c3c-6871c563ddb3)

It will always be the id number at the end of https://youtube.com/embed/[ID HERE]

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/f99da095-f473-439e-a208-a81307e15efa)

**Comment by katjam** [comment]
We could hardcode that first part if you only want to need to input the id and you are certain that your videos will always only come from youtube.

**Comment by katjam** [comment]
@AutumnBarlow I made it so you only have to add the 11 character ID code for the video in guides. So you don't need to worry about the URL anymore.

**Comment by AutumnBarlow** [comment]
I amended to the ID codes and they worked initially but now pull the 404 text through instead.

**Comment by aaaaargZombies** [comment]
## Verified

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/be97fea1-3a05-4b0f-9b51-f9506400b955)
