### ISSUE TITLE
[Bug]: Make search l box look like design

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#337]
## Description

The search box design has regressed a little.

It looks like:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/9f498555-0049-4641-acfc-2c2f28d05bf5)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/d2d0a9cd-5a74-485d-8669-5736e66faffb)

It should look like:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/25518793-57f7-4e18-a946-aa7807954769)

The text does not need to change - but the box should have more padding and an arrow. 

## Implementation notes

- [ ] Check if the arrow was intentionally removed (check with the person who made the commit that removed it). 
- [ ] There was also talk about making more accessible with a submit button - but I think this got mooted? See #275 ?
- [ ] Add hidden label as per: https://github.com/geeksforsocialchange/teamwilder/issues/165#issuecomment-1569946430

**Comment by aaaaargZombies** [comment]
## Verified

It is a bit shorter but I think this is acceptable 

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/b7ee4b8c-9d78-4887-bffb-543f6c16f155)
