### ISSUE TITLE
Stories seem to have videos. Do we add that to the design?

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#343]
Currently they are being added to content in a click here to see video but embed would probably be better.

**Comment by katjam** [comment]
Question: @AutumnBarlow would it be useful to add a video embed to stories?

@undividual if we decide to add, can we fit it in design?

**Comment by undividual** [comment]
I can make it work if Autumn wants it

**Comment by AutumnBarlow** [comment]
It won't be very common so I would leave it as an option to simply include URLs in the body text of what they submit. They won't be common enough to justify having a video embed.

**Comment by katjam** [comment]
OK thanks! I'll close this.
