### ISSUE TITLE
Display a nextdoor nature resource

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#35]
## Acceptance criteria

- [x] #37
- [x] #46
- [x] #47
- [x] #48
- [x] When I add a new nextdoor nature resource in markdown, the site includes it (included in #48 )

## Implementation notes & questions
- All acceptance criteria will probably be standalone tasks and should be converted to issues before commencing work

**Comment by katjam** [comment]
As with the other stuff, lets hardcode the top elements of the loose design and use this to initially get the layout / responsive / template of the view done.

Then when we get to "I can add and edit the nextdoor nature resource in markdown" we can swap out that data to coming from the markdown + JSON decoder.

**Comment by katjam** [comment]
Closing as tasks have been converted.

**Comment by r-ferrier** [comment]
verified in sharded tickets
