### ISSUE TITLE
Display a story

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#36]
## Acceptance criteria

- [x] #64
- [x] #80
- [x] #65
- [x] #66
- [x] When I add a new story in markdown, the site includes it (included in #66 )

## Implementation notes & questions
- All acceptance criteria will probably be standalone tasks and should be converted to issues before commencing work . Can follow same pattern as how #35 was broken up.

**Comment by katjam** [comment]
@undividual I'd like to come up with a better name for case study for user facing copy asap. Any ideas?

**Comment by undividual** [comment]
Hmmm...
"Your stories" / "Your story"
"Real life experience"
"Real world stories"

Why don't you like case studies though? Do you think it's too formal? I can't think of any better phrase to do it which doesn't 'other' the end users.

**Comment by katjam** [comment]
I guess I see a lot where "stories" is used and wanted to come up with something different but maybe it's the best.

Case Study is too formal - like if I'm a person wanting to start a group I want to see "How other's did it!" not "Read a Case Study"

**Comment by kimadactyl** [comment]
a bit abstract maybe but - "i did it"? "in action"?

**Comment by kimadactyl** [comment]
is it just a blog?

**Comment by undividual** [comment]
No, these will be a core part of this site, as a particular type of page which appears and is referenced throughout (havign these is a really core part of their requirement). I wonder if we should consult them on what THEY'D want to call them? Or maybe that's something they expect us to decide

**Comment by kimadactyl** [comment]
for the record i really dont mind case study either

**Comment by katjam** [comment]
> No, these will be a core part of this site, as a particular type of page which appears and is referenced throughout (havign these is a really core part of their requirement). I wonder if we should consult them on what THEY'D want to call them? Or maybe that's something they expect us to decide

I made another issue #59 and suggest for now we go with stories and guides. There is a further question how we present their listing pages #60.

**Comment by katjam** [comment]
@r-ferrier if this has all been carded elsewhere, we can closse.

**Comment by r-ferrier** [comment]
verified in sharded issues
