### ISSUE TITLE
Set up VITE_BASE_URL for CI deploy environs

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#375]
## Description

The base url value is used in meta data. We should configure so it is correct for where app is deployed.

Default is set to: https://nextdoornaturehub.org.uk so this is really more for non-production sites to be "correct".

**Comment by ivan-kocienski-gfsc** [comment]
Do we have a launch domain locked in and ready?

**Comment by katjam** [comment]
Added to netlify config.
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/d1dc8d9e-bb0a-4a71-8a15-5bc9f3cc4688)
