### ISSUE TITLE
Generate documentation about how to use CMS

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#386]
## Description

This is as a guide for members of Team Wilder

Including, but not limited to:
- How to preview content in a PR
- Where to edit content
- How to publish draft & publish

**Comment by aaaaargZombies** [comment]
> - How to preview content in a PR

Will this be dependent on how the repo is managed, ie might not be github

**Comment by aaaaargZombies** [comment]
work begun in the wiki

**Comment by katjam** [comment]
This also needs to be in the readme. The wiki is more what it does  as UAT, not how to do it.

**Comment by katjam** [comment]
Closing as this has been slightly addressed by the README. We can add to later if it proves difficult to use.
