### ISSUE TITLE
Make the purpose & use of the site clearer

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#387]
## User story

A person landing on the home page should be in no doubt what they can do here and how to do it.

## Acceptance criteria

- [x] Do this first: #389 
- [x] The WelcomeP1 is more prominent than the other 2 sections (TBC - let's try it)
- [ ] The featured guide and stories sections have brief intro text

**Comment by katjam** [comment]
This one needs some thought by @undividual and @AutumnBarlow

**Comment by undividual** [comment]
Hi again everyone, I have added to the miro and attached here a screenshot of the homepage with a video embed in the first column for the video Autumn wants to add (if this is possible)

![MVPWireframes_1](https://github.com/geeksforsocialchange/teamwilder/assets/90701712/f1f32f06-ecf5-4653-80ea-68d1926356eb)

**Comment by katjam** [comment]
Closing as we have addressed this in part. And not wanting to add more text.
