### ISSUE TITLE
Content for Home page is easily updatable

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#389]
Noted here:
https://github.com/geeksforsocialchange/teamwilder/pull/333/files#r1227012244

## Acceptance criteria

- [ ] The bulk of the page content for Index is in CMS (e.g. WelcomeP1 etc)

**Comment by AutumnBarlow** [comment]
Here is what we would like to see on the landing page to address this issue:

h1: Welcome to the Nextdoor Nature Hub

h2: This website will help you to help nature.
h2: Here, you will find GUIDES and STORIES. Guides are full of simple, easy-to-understand information in words and videos to help you to take action for nature.
h2:And Stories are where you can read all about what other people are doing where they live and work. They are full of ideas to show you how everyday communities can help nature and wildlife all over the UK. And you can share your story here too!

p: Please explore our website. You can choose Welsh by clicking the button at the top. If you want to get in touch, please email us on [nextdoornature@wildlifetrust.org](mailto:nextdoornature@wildlifetrust.org). We’d love to hear from you!
p: Nextdoor Nature is a project from The Wildlife Trusts. We’re working with communities to bring people together and give everyone the power to help nature flourish – everywhere.
p: Thanks to £5million funding from The National Lottery Heritage Fund, Nextdoor Nature provides you with the advice and support you need to help nature on your doorstep, and leave a lasting natural legacy to mark The Queen’s Platinum Jubilee.

**Comment by ivan-kocienski-gfsc** [comment]
Could we make a special `Page` that has a set of explicit fields that get put in the right place on index?

**Comment by katjam** [comment]
We can do similar to what we did with Submit Story page

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/d7904e4c-53f2-45bb-9e55-c7ab8ea2acdd)
