### ISSUE TITLE
[Bug]: Malformed links on index in the Guides by Theme component

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/teamwilder#408]
## Description

Trying to use the Guides by Theme component and it takes me to the 404 page.

## Steps to reproduce

1. Visit root and click on one of the guides on the right hand side

**Comment by katjam** [comment]
verified on production release. Links work.

e.g. https://nextdoornaturehub.org.uk/guides/reaching-people-in-your-community
