### ISSUE TITLE
[Bug]: Changes to design on submit story page

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#431]
### GFSC work
- [x] formstack theme - padding removed from iframe to allow header/input alignment
- [x] formstack theme - input border color is purple
- [x] formstack theme - border radius set to match images (rounded except bottom left)

### Wildlife Trust Work
- [ ] formstack theme is applied (formstack) [code](https://github.com/geeksforsocialchange/teamwilder/blob/main/formstackTheme.css), [guide](https://help.formstack.com/s/article/Custom-Form-Themes-and-CSS)
- [ ] no typos in copy (formstack)
- [ ] No ellpisis after “studies with images…” under share images (formstack)
- [ ] Hyper link email address in text in left column (CMS)
- [ ] Hyperlink privacy policy so it goes to privacy policy page (CMS)
- [ ] TBC Take out phone number box! (formstack)

## Notes from meeting

NOTE: The actual form is an embed and will be controlled in The Wildlife Trusts formstack - not in this codebase.

Your details heading not in line with rest of column

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/0b485fe3-edd1-402b-a1bf-7aa3dfabce31)

Would be cute if text boxes were rounded like the image — I thought not possible but Ben dabbled in the source code and did it in like a minute, haha — his screenshot attached. Question from Emma — could black outlines be purple?

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/e537c7c7-ae94-4134-889c-ce4ae4b8215c)

Take out phone number box! (TBC - in our testing some users preferred a phone call over email)

“We can contact you wth any questions” typo under email box

No ellpisis after “studies with images…” under share images

Hyper link email address in text in left column

Hyperlink privacy policy so it goes to privacy policy page

**Comment by aaaaargZombies** [comment]
@AutumnBarlow I've updated the CSS theme following feedback from design meeting. It will need to be applied in the same way I descibed in the email I sent you. I've linked to the code and the guide for applied in this issue description but feel free to ask for any more details if you need either here or by email.

**Comment by AutumnBarlow** [comment]
There is a cCc on the Welsh version of the submit your story page.
![image](https://github.com/geeksforsocialchange/teamwilder/assets/102548510/d04df974-5bae-4777-81c7-5211022df82b)

**Comment by katjam** [comment]
@AutumnBarlow I'm leaving this one with you also - but let me know if something needs changing our side. 

I'm curious whether you need the UTM tracking codes as per the image because we included the forms as iframes rather than javascript embeds. I can also speak to Andy about this at a later date. The important thing for right now is that the forms work.

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/f28a1c5f-d136-4667-83b7-18685ddda4aa)

**Comment by AutumnBarlow** [comment]
Closing as the form is now submitting stories to our inbox. We will update with the Welsh and the typo corrections.
