### ISSUE TITLE
Videos have disappeared

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#441]
### Issue

Videos have disappeared - maybe due to merge conflict with adding video descriptions?

Looks like the problem is if the video doesn't have a description then it is considered missing.

- works: http://localhost:5173/guides/all-about-councils-and-local-authorities
- does not work: http://localhost:5173/guides/finding-funding

### Acceptance criteria

- [x] I can see a video when one is included in the content
- [x] Videos are 100% of the width of their column

**Comment by ivan-kocienski-gfsc** [comment]
I can't seem to replicate this on my local machine. video shows up fine on both localhost and the proto dev server.

**Comment by ivan-kocienski-gfsc** [comment]
have checked on both chromium and firefox and it loads okay. #not-a-bug ?

**Comment by ivan-kocienski-gfsc** [comment]
closing this as it seems to work on the prototype server just fine 

![Screenshot_2023-06-19_14-05-32](https://github.com/geeksforsocialchange/teamwilder/assets/109223824/7f67784f-2235-4083-a04c-9eea5ddef0c1)

**Comment by katjam** [comment]
This seems to have resolved itself again:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/ef857b6d-494a-4764-acbe-1da00f3b4ac9)
