### ISSUE TITLE
Leading (gap between lines) on main title is too wide (Ben to supply logo)

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#451]
## Acceptance Criteria

- [ ] The line-height is reduced from original:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/954335f0-493e-467a-8e5f-5b77542f985b)

**Comment by ivan-kocienski-gfsc** [comment]
Waiting for logo, flagging as question.
