### ISSUE TITLE
[Bug]: index.md page not showing in cms

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/teamwilder#457]
## Description

We source content for the left column if the index page from a markdown file. This should be editable in the cms so the wild life trust can keep it up to date.

For some reason when you enter the pages section of the cms this page is not visible.

**Comment by aaaaargZombies** [comment]
issue arising from #389  /  #446

**Comment by aaaaargZombies** [comment]
Pages in the CMS are named using the title field from font matter, I was looking for the filename. A very silly mistake, apologies to all who have to read the git log.

**Comment by katjam** [comment]
I was gonna ask that!

**Comment by katjam** [comment]
Won't fix. We were looking for the wrong name.
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/ff5401e7-8cef-4a58-acec-fc6392506185)
