### ISSUE TITLE
Add video description to guide CMS

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/teamwilder#459]
## User story

As an admin I want to be able to add a (optional) video description to guide videos

## Acceptance criteria

- [ ] guides have video desciption field in CMS
- [ ] can be filled by admin
- [ ] will show up on Guide page
- [ ] can be removed by admin

## Implementation notes & questions

Should just be an edit in the CMS

**Comment by katjam** [comment]
Verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/58ad4413-317f-4f8f-b30f-6b0be6f14eb4)
