### ISSUE TITLE
I can see a teaser for a nextdoor nature resource

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#46]
## Acceptance Criteria

- [x] #75
- [x] A resource teaser links to it's single view page
- [x] A resource teaser contains an image
- [x] A resource teaser contains a short summary (this will be a new field on Resource and should be limited to xx chars)
- [ ] #47 (will be done after)

**Comment by katjam** [comment]
This will eventually be the "alphabetical by default" resource index (with search / filter). Some AC and a staged plan / thought need to go into this. Initially we can just display a couple teasers on the index page.

**Comment by katjam** [comment]
@undividual I think in the wireframe for Resource, there is not an image - but we want one for teasers. Do we want to also display the same image on the single page?

**Comment by undividual** [comment]
Yes good point — we should include the image within the case studies as well. I feel like design wise they might like it to be big and full width, but I worry this puts too much pressure on some of the slightly more shit images we'll inevitably have for some case studies. Happy to talk about where/how it should sit on the main guide page but do think they need to be in there, correct.

**Comment by katjam** [comment]
@aaaaargZombies Note that we just confirmed the requirement for teaser to have an image. Please also add to the Guide content type at this time. I wasn't sure if you want are working your way down the list, so didn't convert to own issue.

**Comment by r-ferrier** [comment]
verified: Teasers exist in welsh and english

![Screenshot 2023-05-29 at 16 36 57](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/d32e5254-e60c-4a15-bc7e-1890f826d121)
![Screenshot 2023-05-29 at 16 36 50](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/8e7aaaa7-7261-467e-bd8f-ce9a4156f85a)
