### ISSUE TITLE
[Bug]: fix link appearance

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#463]
## Acceptance criteria

- [ ] All links or link-like buttons are underlined with underline colour at ~50%
- [ ] All links underline goes to 100% colour on hover

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/885b6d41-ce41-4df2-83f4-88c8416e4b59)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/d20b1e50-2ca3-4c57-a27f-dd1d187c22b4)
