### ISSUE TITLE
Language toggle written in the opposite language

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#464]
## Issue

When viewing the page in welsh as an english speaker, or in english as a welsh speaker, I cannot find out how to change to my language. We should translate the copy into the correct language.

- [x] `Newid i'r Saesneg` becomes `Switch to English`
- [x] `Switch to Welsh` becomes `Newid i'r Gymraeg`
- [ ] copy is signed off by Autumn

**Comment by r-ferrier** [comment]
@AutumnBarlow we noticed this usability glitch while doing an accessibility sweep - are you happy with these suggested changes?

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/7dc142cc-01f6-4428-960c-38a7d6ba2d4a)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/55cb7ec4-d338-4954-a769-d6231a091a84)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/3f166cfc-f43d-470b-89f5-f4ca09a349b1)
