### ISSUE TITLE
Make guide header look like wireframe

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#467]
<img width="750" alt="Screenshot 2023-06-20 at 11 58 36" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/38ef24ad-38d2-4ca5-a429-ce480d08d51a">

## Acceptance criteria

- [ ] Header contains summary
- [ ] Header contains image
- [ ] Header contains image credit/caption
- [ ] Header does not contain go back to previous page link

**Comment by r-ferrier** [comment]
waiting for confirmation that this is the correct design

**Comment by r-ferrier** [comment]
is good to go!

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/58c382f6-002c-4684-9739-7da609e2fc16)
