### ISSUE TITLE
Add icons to teasers and a key for them

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#47]
# Description

Guides have content types that should be visible to readers so they can see if a Guide has
- Video content
- Audio content
- Printable version
- Text content

## Resources 

Get icons here: https://www.dropbox.com/sh/5rxaz26opzhmzco/AAD1RISCvDjEwnSwhpOeLDO3a?dl=0

## Acceptance Criteria
- [ ] There is an icon key on pages where teasers appear (currently search results `/guides` and index `/`)
- [ ] There is a title/alt text covering the icons description wherever icons appear

## Implementation notes
- [ ] Procure icon graphics (dropbox above)
- [ ] When pulling in teaser data, determine what type of content each guide has
- [ ] Decide what to do about actions - we may not have access to the data we need from the json feed #31 
- [ ] Render icons in teaser if that type of content is present in the full guide.
- [ ] use a partial / helper functions to render the Guide's icon fields into the correct HTML

**Comment by undividual** [comment]
FYI, icons have been refined as shown in this design. I need to prepare .eps files of these 'teardrop' icons to supply to you.

![MVPWireframes_1Homepage](https://user-images.githubusercontent.com/90701712/232233820-7d14ddb8-3655-446b-ab67-5f134f33262d.jpg)

**Comment by katjam** [comment]
Won't fix. There is not significant differnce to content of guides
