### ISSUE TITLE
[Bug]: print css regressions

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/teamwilder#502]
## Description

Elements we have added to guides after the print css PR have not been excluded from print.

**Comment by katjam** [comment]
verified:
[Faith Groups and Lottery Funding _ The Nextdoor Nature Hub.pdf](https://github.com/geeksforsocialchange/teamwilder/files/11948579/Faith.Groups.and.Lottery.Funding._.The.Nextdoor.Nature.Hub.pdf)
