### ISSUE TITLE
[Bug]: Homepage layout broken at tablet

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#507]
## Description

<img width="1022" alt="Screenshot 2023-06-21 at 10 20 21" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/4ad8197c-68f5-432e-bc63-e11a500d2081">

## Issue

It looks like the submit your story box has been added to a column flex container that switches to row at tablet. Needs to be placed outside this in a flex container that remains a column at all sizes.

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/16da2a50-140d-4c3f-8a07-22ea7c3ef66c)
