### ISSUE TITLE
[Bug]: adding link underlines has introduced a regression in the footer nav

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/teamwilder#508]
## Description

There should be a visual indication of which page you are on in the footer nav so you don't try and click it.

![image](https://github.com/geeksforsocialchange/teamwilder/assets/6824891/c0add748-1d3a-48b1-a8d9-f654e42986e5)

## Acceptance criteria

- [ ] bolder for current page as suggested by Emma

**Comment by aaaaargZombies** [comment]
@undividual comments...

> Oh sorry, some wires crossed here. This doesn't work.
Underlines should always be the thinner version. Could we either do:
Type goes bolder
OR
Type becomes teal
OR
You mentioned another site does a kind of, highlight behinf feature?

**Comment by r-ferrier** [comment]
@undividual Devil's advocate here: do we really need this, especially as it's in the footer? It's not a place I would expect to go to see where I am - I would expect the design of links in footers to usually look the same on every page, like a site map. Is adding another flavour of text decoration to an already decorated link potentially a bit confusing?

**Comment by undividual** [comment]
Yep, don't think the request originally came from me, it was a @katjam suggestion that it should happen (I think!) — very happy to simply not do it, I think I thought it was an accessibility requirement.

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/caf27e1f-3584-4a68-b4d0-acedaea3a1cc)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/79fc24b1-341c-4bad-876e-a0a59bb246a2)
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/75d18b47-30da-4fd7-991b-907751c423ea)
