### ISSUE TITLE
Add infrastructure for ancillary pages

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#51]
## Acceptance criteria

- [x] I can add an ancillary page in markdown (e.g. privacy, about, how to use site...)
- [ ] #101

### Proposed potential pages in footer design
 - [ ] #103
 - [ ] #104
 - [ ] Privacy (needed if we do #32 or #34)
 - [ ] #105
 - [ ] Submit your own Case study - blocked by #34

**Comment by r-ferrier** [comment]
verified in sharded issues
