### ISSUE TITLE
[Bug]: When one guide is found it says '1 guides found'

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#511]
## Description

<img width="872" alt="Screenshot 2023-06-21 at 12 09 21" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/5cd42634-79fe-478c-a1cc-304ed7cdb03d">

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/55f4e332-9f8f-47f0-bc9f-dcaaac5761a4)
