### ISSUE TITLE
[Bug]: Cms required/ unrequired fields - are we managing these correctly

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#539]
## Description

While doing the UAT docs I've noticed that we maybe have some fields set up sub optimally in the cms config - for example, image is a required widget, but then the fields are all optional, which I *think* could allow someone to upload an image without alt text or alt text without an image? Images should be optional but if they are added, then alt text and an image should be requirements. This is a pattern used throughout so it may just be that this is the way to set it up but would like to investigate to check

**Comment by katjam** [comment]
Closing as should be addressed by #458
