### ISSUE TITLE
Add print css to single guide pages & a print button?

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#57]
## Acceptance Criteria

- [ ] I can print a resource guide to paper

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/224542521-93cb7a01-7e5c-463b-88f9-3c6e1ef0b6f5.png)

**Comment by aaaaargZombies** [comment]
## verified

https://github.com/geeksforsocialchange/teamwilder/assets/6824891/61d6a015-a2d9-4269-aa4e-26d2271c8dd2
