### ISSUE TITLE
[Bug]: Thumbnails for related stories on a guide page squash together if more than one

### ISSUE THREAD

**Issue by AutumnBarlow** [geeksforsocialchange/teamwilder#577]
If I add more than one related story to a guide page, they come out looking squashed and uneven (Chrome) 

See the "Taking over green space" page https://team-wilder-proto.pages.dev/guides/taking-over-green-space-in-your-area

Screenshot 
![image](https://github.com/geeksforsocialchange/teamwilder/assets/102548510/385ae121-881d-42e4-b7c5-d6a0bb267d5f)

**Comment by AutumnBarlow** [comment]
Same issue with two related stories.
![image](https://github.com/geeksforsocialchange/teamwilder/assets/102548510/b4cd1991-db15-4c2a-acbd-71fde00846d2)

**Comment by katjam** [comment]
Thanks @AutumnBarlow I'll get this fixed. I'm glad you are using the related stories fields!

**Comment by r-ferrier** [comment]
Just came here to note this issue! I'm going to fix it right now because it will take me just 5 mins

**Comment by katjam** [comment]
verified
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/b9800b8c-6ffa-4b2b-9e50-b532ad22f54b)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/b8220436-bd4c-4e32-bf83-10079c50fc9c)

![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/3a593610-9815-48c0-82c5-d3b160369194)
