### ISSUE TITLE
Rename public facing instances of Resource and Case Study

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#59]
## Acceptance Criteria (TBC - wait until agreed)

- [x] #72
- [x] #68
- [x] #73
- [x] #69

## Plan

- [ ]

**Comment by katjam** [comment]
@undividual#7924 (mostly) shall we call them guides and stories for now ?

**Comment by undividual** [comment]
Yes, I am happy with this!

**Comment by r-ferrier** [comment]
Verified:
<img width="540" alt="Screenshot 2023-05-29 at 17 12 00" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/e0752bcb-d437-4bda-8b24-5b3ab0caf8e1">
<img width="539" alt="Screenshot 2023-05-29 at 17 11 53" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/295a992d-610a-4229-9738-3a746deee4d4">
<img width="547" alt="Screenshot 2023-05-29 at 17 11 38" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/d09532b1-e053-4c2c-81df-eed5dfb3ce41">
