### ISSUE TITLE
[Bug]: Unable to refresh page or visit pages directly on netlify

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#592]
## Description

[from emails to Emma]

Top issues:
 
Does not reload on refresh.
Cannot right click to open a guide or story as new tab (in Chrome)
 
Other issues:
 
The page not found page is not the 404 badger
There is no way of sending someone a URL to the guides page – it seems to be built into the search facility (this is probably something you cannot fix but I wish we knew about it before because it would have been one of my essentials to have an actual page I could link to)
Formstack not working – people cannot submit a story, I did a test yesterday

**Comment by r-ferrier** [comment]
Think this is linked to elm and netlify config clashes. We;re going to try Katja's suggested fix first, and if that doesn't work, will try adding a redirects file again, with the caveat that this will break cloudflare and will need revisiting when we move to azure https://github.com/geeksforsocialchange/teamwilder/issues/151

**Comment by katjam** [comment]
verified:
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/09af5e9b-5954-4cc5-a3e6-0ff7f12fbc98)

Also visited links and deep links with refresh.
