### ISSUE TITLE
I can add and edit the  story in markdown

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#66]
- [ ] I can add a story in markdown
- [ ] When I add a new story in markdown, the site includes it
---
- [ ] A story can be in english or welsh?

**Comment by r-ferrier** [comment]
@katjam @undividual As stories are user submitted, are they able to be translated? And if so, do we add a field to the story form to say whether they are submitting in english or welsh? Or do we do this via a hidden field, using whichever language they are currently viewing the site in?

**Comment by undividual** [comment]
@r-ferrier So even though they are user submitted they still absolutely have to be translated. The questions around language submission are really interesting though — I think it should be a hidden field based on the language they're viewing the site in. None of these case studies would go live without a real person at the WTs checking them anyway, so I think it would be okay, and better than making the user select (but I bow to others who may have greater knowledge of best practice in this area)

**Comment by katjam** [comment]
Yes. We'll use the same translation system as for the guides in the markdown. We may re-jig when we find out how the CMS wants to deal with it, but I think I'll use a markdown field for now and fallback to English if the Welsh does not exist (with a notice about that)

**Comment by r-ferrier** [comment]
verified:
<img width="452" alt="Screenshot 2023-05-29 at 16 44 07" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/5144c356-ae64-4295-836b-d2de4010cef0">
![Screenshot 2023-05-29 at 16 44 47](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/2d956586-244f-4253-a008-20aacfab6da4)
![Screenshot 2023-05-29 at 16 44 52](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/2154d2a6-bf53-4c6b-94d5-66fd0710c5cf)
