### ISSUE TITLE
Set up Decap/Netlify CMS

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#7]
Tasks:

- [ ] Set up CMS
- [ ] Add welsh locale to CMS
- [ ] Consider/discuss enabling google translate for english text blocks whilst viewing pages in welsh  

Initial research into l18n within the CMS, enabling non tech staff to manage translated copy:

Netlify CMS is now Decap CMS & includes localisation options.

More info on these here:
https://www.npmjs.com/package/netlify-cms-locales
https://www.netlifycms.org/docs/configuration-options/#locale

Can be added to the config.yml like so: 
```
locale: 'cym'
```

And in js like so: 

```
import CMS from 'netlify-cms-app';
import { de } from '
netlify-cms-locales';

CMS.registerLocale('cym', cym);
```

Defaults to english when translation is missing - would we need to do something at this point to force google translate to kick in? More info on this here:

https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites
https://developers.google.com/search/docs/specialty/international/localized-versions

**Comment by katjam** [comment]
Wildlife Trusts IT people would prefer us to use: 

Team [SAML single sign-on | Netlify Docs](https://docs.netlify.com/accounts-and-billing/team-management/saml-single-sign-on/)

> To circle back on one of the points related to authentication. During the call we discussed using Github as the authentication mechanism for the Netlify CMS. However on reviewing their documentation it appears they support Azure AD authentication which would be our preference as it would enable us to manage access via our existing infrastructure.
- Tim

**Comment by katjam** [comment]
@r-ferrier Have you looked into the Azure integration? Do you need me to get account creds from them to test it?

**Comment by r-ferrier** [comment]
Self hosting netlify:

Once all the config stuff is added to our repo you need to authenticate the cms to get access to the repo using an oauth app, which needs to be hosted elsewhere.

Here's the walkthrough I found of someone else doing this
- https://cleavr.io/cleavr-slice/how-to-deploy-netlify-cms-to-your-own-self-hosted-server

And here's the approach I was thinking of for our repo + cloudflare
- https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
- https://github.com/gr2m/cloudflare-worker-github-oauth-login

**Comment by katjam** [comment]
@r-ferrier This is my admin/index.html

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <!-- We might eventually want to add to the project - but this is quick -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```

**Comment by katjam** [comment]
And this is the head of the `config.yml`

```

 

backend:
  name: github
  repo: TheLabCollective/vector
  branch: main
media_folder: "/src/assets/images/uploads" # Media files will be stored in the repo under assets/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads
collections:
```

**Comment by r-ferrier** [comment]
I tried this but was still getting some grumbling - will have another quick look tomorrow at the netlify settings though when my mind is a bit fresher

![Screenshot 2023-04-18 at 15 29 47](https://user-images.githubusercontent.com/46496391/232846852-7ed65a26-daf0-4949-8085-0bcc08eb0fd5.png)

**Comment by katjam** [comment]
Verified: 
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/b059a894-5135-4148-8eac-ad601977068a)
