### ISSUE TITLE
Display a story based on url slug

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/teamwilder#80]
As a user I would like to see different stories based on which link I click.

## Acceptance Criteria

- [ ] different stories shown based on slug
- [ ] if story does not exist then show message

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I think this will be done as part of the other Story related work, but since you are working on it, I'll pop it in the milestone for visibility.
