### ISSUE TITLE
Add tests to assert markdown is being parsed correctly

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/teamwilder#86]

**Comment by ivan-kocienski-gfsc** [comment]
This has been done as part of PR #89

**Comment by r-ferrier** [comment]
verified: tested in Page.elm, Story.elm & Guide.elm

<img width="555" alt="Screenshot 2023-05-29 at 16 32 59" src="https://github.com/geeksforsocialchange/teamwilder/assets/46496391/bba14942-dfb6-455a-9c87-55c1b5b96d27">
