### ISSUE TITLE
I can see usage data in Hotjar

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#93]
## Acceptance criteria

- [ ] add Wildlifes trust's hotjar code to `head` of `index.html`

## Implementation details

- has been tested with test hotjar account #399
- for devs login details to this test account in bitwardin

**Comment by katjam** [comment]
Question for The Wildlife Trusts. Is this important?

**Comment by undividual** [comment]
Reply from the wildlife trusts (Autumn): Yes, I think this is important — but Autumn cannot answer definitively. Need to reach out directly to Tim to find out.

**Comment by katjam** [comment]
Agree. This has been repeatedly cited as important by Alice also.

**Comment by aaaaargZombies** [comment]
## Notes

- register hotjar account
- create widget for out cloudflare test URL
- add proived script top head

**Comment by aaaaargZombies** [comment]
@AutumnBarlow I through this with a dummy hotjar account and all works as expected.

We'll just need the snippet your real hotjar account provides linked to the correct URL you will be using with the public.

**Comment by katjam** [comment]
@aaaaargZombies IS this a GFSC hotjar account that we can verify in - or one only you have access to ?
